$axure.loadCurrentPage({
  "url":"资讯详细页面_1.html",
  "generationDate":new Date(1383038971745.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/系统登录默认页/bg.jpg",
    "width":1000,
    "height":750},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"0a15db67c87547528ec05242e2469439",
    "type":"Axure:Page",
    "name":"资讯详细页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1c22699d94a84f1d81ef0363da8798da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":162},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfb4100546ad41d5993e06206ee818ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":162},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 资讯管理",
                      "target":{
                        "targetType":"page",
                        "url":"资讯管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b7bf16214e846c493e2c176517c0790",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":162},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c095a3d29f4349b9a7b0d71474944568",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":162},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f88516d1b6649b0b66c91e5932fe116",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":70},
            "size":{
              "width":152,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abeded302a1e466c8368b00abbdd9cc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":70},
                "size":{
                  "width":152,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69fade9ae391486e98b75a40fcf5f23d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":200},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44e59385c3cc4fc684280d3f8894b0d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":200},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"768675781c6e4717ba970e5e21fe74e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":505,
              "y":226},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dac8fcaf3b34f4eb33cf530f8b333f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":505,
                  "y":226},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f61ce451f6f411d85faf804e3698476",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":240},
            "size":{
              "width":650,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2f2cfb1eee847e8af090e1fa62c5e5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":240},
                "size":{
                  "width":650,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57cd57e0d88a4a4da09c6a47b7393a91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":288},
            "size":{
              "width":590,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0979e1a587b24352a3e24af70d02d049",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":288},
                "size":{
                  "width":590,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a94797435b54e5f845af2a6aa24db84",
          "label":"菜单",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":170},
            "size":{
              "width":141,
              "height":520}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"8ec609f9afed420cab1280685899a781",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"931d215284b34323bf27beb95f8072cc",
                  "label":"",
                  "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":10}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"f7504d85b8d449428ec744664ec99d8b",
                  "label":"",
                  "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":18},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eeb166a576294829be880f53d03e0699",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":18},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"03a331d40dfc4e5c9c28119c3a2b0b18",
                  "label":"",
                  "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":43},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"11243917345e4d33a84ea317e8066052",
                  "label":"",
                  "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":51},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d3959b07b493492bae7d82f8f0af317f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":51},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 注册新会员",
                              "target":{
                                "targetType":"page",
                                "url":"注册新会员.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"be3c6ef7193a47a3b982320de0047f8b",
                  "label":"",
                  "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":76},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"ffc87f1a7e4e423b86f81b1f375ebab1",
                  "label":"",
                  "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":84},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a779db65be7b4877824bf7bee7729948",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":84},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 汇款充值",
                              "target":{
                                "targetType":"page",
                                "url":"汇款充值.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d6fc018217284af49f0aac772c7ee174",
                  "label":"",
                  "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":109},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"b204bfd8d9e448d38bc0af6ca343ca33",
                  "label":"",
                  "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":117},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b9506609191447a481c56bcb95b14266",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":117},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 报单购物",
                              "target":{
                                "targetType":"page",
                                "url":"报单购物.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1614c046120747d3b2e0a9c8f749c802",
                  "label":"",
                  "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":142},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"f914970deb534e728bead057e445fcc6",
                  "label":"",
                  "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":150},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a1edb9d5f81d45c2b3d12fc97cf9b5b8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":150},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 奖励查询",
                              "target":{
                                "targetType":"page",
                                "url":"奖励查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9021215e104f47d09615dc4de8ea6b65",
                  "label":"",
                  "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":175},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"47ef087e11d24d169b2768a6ba4ee088",
                  "label":"",
                  "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":183},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e4cd854b2fd44792bad19489aa76c40b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":183},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cfaf6f645a2943d4b54e1e8a29dfbc0a",
                  "label":"",
                  "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":26,
                      "y":217},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"21194e0ac43e414a8919c48afe1d46d5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":26,
                          "y":217},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"99ff731ec84446e9af50adb2b9332943",
                  "label":"",
                  "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":26,
                      "y":241},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5621a52bd81d4b208b7b41098b00a1ed",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":26,
                          "y":241},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 资讯管理",
                              "target":{
                                "targetType":"page",
                                "url":"资讯管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"83f1c1afcd064cda8a378e625c280d6e",
                  "label":"",
                  "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00,
                      "opacity":1},
                    "location":{
                      "x":26,
                      "y":267},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"773c756701a346aea62aa1e7ba842b22",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00,
                          "opacity":1},
                        "location":{
                          "x":26,
                          "y":267},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 下载中心",
                              "target":{
                                "targetType":"page",
                                "url":"下载中心.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e58223b315154b808fc5441f76756408",
                  "label":"",
                  "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":26,
                      "y":290},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ac08d51dcf5c4eeaa39e9315127fa714",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a94797435b54e5f845af2a6aa24db84",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":26,
                          "y":290},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 留言管理",
                              "target":{
                                "targetType":"page",
                                "url":"留言管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"38521fc10792487d995851d6a93dc972",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":307,
              "y":470},
            "size":{
              "width":48,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c513d6fd118e4446b5decbd616c2b513",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":307,
                  "y":470},
                "size":{
                  "width":48,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资讯详细页面/u59.png"}},
{
          "id":"274120bb9b8b48ba981f1bb2e37b5fa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":307,
              "y":518},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8e2f0227c194ca69650878178f38ad1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":307,
                  "y":518},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aea26c6acab74fa4a80ba33d47c48984",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":250},
            "size":{
              "width":600,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/资讯详细页面/u63_line.png"}},
{
          "id":"22be62c193a2469bb498c9b7556b1d93",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":460},
            "size":{
              "width":600,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/资讯详细页面/u63_line.png"}},
{
          "id":"e4d435783d734d10890d1183c8b43357",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xA5006600},
                "linePattern":"solid"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFDFEACA},
            "location":{
              "x":779,
              "y":510},
            "size":{
              "width":70,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF6DB847},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59e3770a223d42b0b350e4c6027518dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xA5006600},
                    "linePattern":"solid"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDFEACA},
                "location":{
                  "x":779,
                  "y":510},
                "size":{
                  "width":70,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF6DB847},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 下载中心",
                      "target":{
                        "targetType":"page",
                        "url":"下载中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/公告详细页面/u57.png",
            "mouseOver~":"images/公告详细页面/u57_mouseOver.png"}},
{
          "id":"fc9aaa1144b84f30aae2e1c4217fdebb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":306,
              "y":15},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45ceba7858af40cdb2d5ad3e72ad1d75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":15},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e37198047d14ed1ba56c6e47eeceb51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":408,
              "y":15},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44043365cae249998cd9887012e25176",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":408,
                  "y":15},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee2de1b328f34ed8bfdd715e0022f820",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":785,
              "y":15},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5878612d2e6421da9d7406b4f45d3c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":785,
                  "y":15},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改本人密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改本人密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"959cb7ba69874a819f5d0d3a38564fbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":868,
              "y":15},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaa672f66e6b45a589d7c5c813a20861",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":868,
                  "y":15},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63039c561c404bf38eee856d0c50a35b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":617,
              "y":15},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7227b2f6bb14ce8a363f35bab37991f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":617,
                  "y":15},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8654ba2313b547eba1b749a45c0edd62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":15},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69160a87110546e0867c7a9d96358ae4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":708,
                  "y":15},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75f8311a8ced4f1a8c94a3162a0cc9a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":737,
              "y":15},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e52331c39f3140dca073be6dce6e6973",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":737,
                  "y":15},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u121.png"}},
{
          "id":"5ecb6da808e14eb681e8d6f3fde216d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":15},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4746eca69d1f45dc882806cc819427e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":15},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85b7f4d7809a4f9e9142312565786969",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":671,
              "y":15},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb87228bbaf646d4ac7ae1a8a5984756",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":671,
                  "y":15},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6eff07b9e2614576b48102ff32578c1e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":526,
              "y":14},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"107bd2505ec447c0a013427c44850211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":526,
                  "y":14},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 购物车",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u127.png"}},
{
          "id":"38bd4e39de6043e0b1f4623d05f7d2b3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":3},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0939553963024364a6354916340b72e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":542,
                  "y":3},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/系统登录默认页/u129.png"}},
{
          "id":"c8bd029c8787489fb55c77d019fe55b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":547,
              "y":1},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47d3c368c0c84caf83fc65cb4a02a1c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":547,
                  "y":1},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "d2415d04c3894ee2a19022d44e11f35b":{
      "packageId":"d2415d04c3894ee2a19022d44e11f35b",
      "type":"Axure:Master",
      "name":"nav",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7837bfaf60f741f3a6519b77012fd40a",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"7a89eecc0e584f76adbdcdcf2a6c58e7"}]}},
    "7a89eecc0e584f76adbdcdcf2a6c58e7":{
      "packageId":"7a89eecc0e584f76adbdcdcf2a6c58e7",
      "type":"Axure:Master",
      "name":"nav1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"82d5041198434b178bff196e00dfbfe6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":141,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7824ebb366034aba98ee9785a7394f11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":141,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg"}}]}}},
  "objectPaths":{
    "1c22699d94a84f1d81ef0363da8798da":{
      "scriptId":"u0"},
    "bfb4100546ad41d5993e06206ee818ff":{
      "scriptId":"u1"},
    "5b7bf16214e846c493e2c176517c0790":{
      "scriptId":"u2"},
    "c095a3d29f4349b9a7b0d71474944568":{
      "scriptId":"u3"},
    "1f88516d1b6649b0b66c91e5932fe116":{
      "scriptId":"u4"},
    "abeded302a1e466c8368b00abbdd9cc5":{
      "scriptId":"u5"},
    "69fade9ae391486e98b75a40fcf5f23d":{
      "scriptId":"u6"},
    "44e59385c3cc4fc684280d3f8894b0d3":{
      "scriptId":"u7"},
    "768675781c6e4717ba970e5e21fe74e6":{
      "scriptId":"u8"},
    "6dac8fcaf3b34f4eb33cf530f8b333f5":{
      "scriptId":"u9"},
    "4f61ce451f6f411d85faf804e3698476":{
      "scriptId":"u10"},
    "e2f2cfb1eee847e8af090e1fa62c5e5c":{
      "scriptId":"u11"},
    "57cd57e0d88a4a4da09c6a47b7393a91":{
      "scriptId":"u12"},
    "0979e1a587b24352a3e24af70d02d049":{
      "scriptId":"u13"},
    "7a94797435b54e5f845af2a6aa24db84":{
      "scriptId":"u14"},
    "931d215284b34323bf27beb95f8072cc":{
      "scriptId":"u15",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u16",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u17"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u18"}}},
    "f7504d85b8d449428ec744664ec99d8b":{
      "scriptId":"u19"},
    "eeb166a576294829be880f53d03e0699":{
      "scriptId":"u20"},
    "03a331d40dfc4e5c9c28119c3a2b0b18":{
      "scriptId":"u21",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u22",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u23"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u24"}}},
    "11243917345e4d33a84ea317e8066052":{
      "scriptId":"u25"},
    "d3959b07b493492bae7d82f8f0af317f":{
      "scriptId":"u26"},
    "be3c6ef7193a47a3b982320de0047f8b":{
      "scriptId":"u27",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u28",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u29"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u30"}}},
    "ffc87f1a7e4e423b86f81b1f375ebab1":{
      "scriptId":"u31"},
    "a779db65be7b4877824bf7bee7729948":{
      "scriptId":"u32"},
    "d6fc018217284af49f0aac772c7ee174":{
      "scriptId":"u33",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u34",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u35"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u36"}}},
    "b204bfd8d9e448d38bc0af6ca343ca33":{
      "scriptId":"u37"},
    "b9506609191447a481c56bcb95b14266":{
      "scriptId":"u38"},
    "1614c046120747d3b2e0a9c8f749c802":{
      "scriptId":"u39",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u40",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u41"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u42"}}},
    "f914970deb534e728bead057e445fcc6":{
      "scriptId":"u43"},
    "a1edb9d5f81d45c2b3d12fc97cf9b5b8":{
      "scriptId":"u44"},
    "9021215e104f47d09615dc4de8ea6b65":{
      "scriptId":"u45",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u46",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u47"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u48"}}},
    "47ef087e11d24d169b2768a6ba4ee088":{
      "scriptId":"u49"},
    "e4cd854b2fd44792bad19489aa76c40b":{
      "scriptId":"u50"},
    "cfaf6f645a2943d4b54e1e8a29dfbc0a":{
      "scriptId":"u51"},
    "21194e0ac43e414a8919c48afe1d46d5":{
      "scriptId":"u52"},
    "99ff731ec84446e9af50adb2b9332943":{
      "scriptId":"u53"},
    "5621a52bd81d4b208b7b41098b00a1ed":{
      "scriptId":"u54"},
    "83f1c1afcd064cda8a378e625c280d6e":{
      "scriptId":"u55"},
    "773c756701a346aea62aa1e7ba842b22":{
      "scriptId":"u56"},
    "e58223b315154b808fc5441f76756408":{
      "scriptId":"u57"},
    "ac08d51dcf5c4eeaa39e9315127fa714":{
      "scriptId":"u58"},
    "38521fc10792487d995851d6a93dc972":{
      "scriptId":"u59"},
    "c513d6fd118e4446b5decbd616c2b513":{
      "scriptId":"u60"},
    "274120bb9b8b48ba981f1bb2e37b5fa1":{
      "scriptId":"u61"},
    "f8e2f0227c194ca69650878178f38ad1":{
      "scriptId":"u62"},
    "aea26c6acab74fa4a80ba33d47c48984":{
      "scriptId":"u63"},
    "22be62c193a2469bb498c9b7556b1d93":{
      "scriptId":"u64"},
    "e4d435783d734d10890d1183c8b43357":{
      "scriptId":"u65"},
    "59e3770a223d42b0b350e4c6027518dd":{
      "scriptId":"u66"},
    "fc9aaa1144b84f30aae2e1c4217fdebb":{
      "scriptId":"u67"},
    "45ceba7858af40cdb2d5ad3e72ad1d75":{
      "scriptId":"u68"},
    "0e37198047d14ed1ba56c6e47eeceb51":{
      "scriptId":"u69"},
    "44043365cae249998cd9887012e25176":{
      "scriptId":"u70"},
    "ee2de1b328f34ed8bfdd715e0022f820":{
      "scriptId":"u71"},
    "e5878612d2e6421da9d7406b4f45d3c0":{
      "scriptId":"u72"},
    "959cb7ba69874a819f5d0d3a38564fbc":{
      "scriptId":"u73"},
    "eaa672f66e6b45a589d7c5c813a20861":{
      "scriptId":"u74"},
    "63039c561c404bf38eee856d0c50a35b":{
      "scriptId":"u75"},
    "c7227b2f6bb14ce8a363f35bab37991f":{
      "scriptId":"u76"},
    "8654ba2313b547eba1b749a45c0edd62":{
      "scriptId":"u77"},
    "69160a87110546e0867c7a9d96358ae4":{
      "scriptId":"u78"},
    "75f8311a8ced4f1a8c94a3162a0cc9a4":{
      "scriptId":"u79"},
    "e52331c39f3140dca073be6dce6e6973":{
      "scriptId":"u80"},
    "5ecb6da808e14eb681e8d6f3fde216d4":{
      "scriptId":"u81"},
    "4746eca69d1f45dc882806cc819427e4":{
      "scriptId":"u82"},
    "85b7f4d7809a4f9e9142312565786969":{
      "scriptId":"u83"},
    "cb87228bbaf646d4ac7ae1a8a5984756":{
      "scriptId":"u84"},
    "6eff07b9e2614576b48102ff32578c1e":{
      "scriptId":"u85"},
    "107bd2505ec447c0a013427c44850211":{
      "scriptId":"u86"},
    "38bd4e39de6043e0b1f4623d05f7d2b3":{
      "scriptId":"u87"},
    "0939553963024364a6354916340b72e9":{
      "scriptId":"u88"},
    "c8bd029c8787489fb55c77d019fe55b6":{
      "scriptId":"u89"},
    "47d3c368c0c84caf83fc65cb4a02a1c2":{
      "scriptId":"u90"}}});