$axure.loadCurrentPage({
  "url":"注册详细确认.html",
  "generationDate":new Date(1383038955494.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/系统登录默认页/bg.jpg",
    "width":1000,
    "height":750},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"c002bba98aa04c13a624f686f626be6c",
    "type":"Axure:Page",
    "name":"注册详细确认",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"460aff69d326454db412d2ce1514ea7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":162},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1639b7318f09462d975df77e011bdabf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":162},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2168250cea454bf598284ca131292b39",
          "label":"菜单",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":170},
            "size":{
              "width":141,
              "height":520}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"12de07e4db6f49f3b059821264074737",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"26ee39431e494812b8f7eb29200591fd",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":10}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"8738c122bb0b4dd8b9cfc8b7b38e1aa4",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":18},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9593b9c88fbb402d880eb0aef1d8a1d6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":18},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ae9a22af6b044161a5d37c8a60dcb285",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":43}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"ef85111489db42f0b199f546178a9380",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":51},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"540aa35d3a114afa9f9ecd8bac382116",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":51},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 注册新会员",
                              "target":{
                                "targetType":"page",
                                "url":"注册新会员.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"06db65c496254602ae8cdc8e6ba4ebf1",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":176},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"3f130c4faa5d4162b587e622fa660bcc",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":184},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5564cb085e4a44cb8645ea18e70d45de",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":184},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 汇款充值",
                              "target":{
                                "targetType":"page",
                                "url":"汇款充值.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"efbde381c9b44cc999e27d003ff04553",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":209},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"63472a5695ee4506847c7035bc3de05f",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":217},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"983379fdf753407a8e5f2f72535f853b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":217},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 报单购物",
                              "target":{
                                "targetType":"page",
                                "url":"报单购物.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e32942c026e7497fbe38cf8487aa0629",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":242},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"96530caba9e54ac789c8c1f45fb6caa1",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":250},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a48922b90d7d4e12a393b824206712cf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":250},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 奖励查询",
                              "target":{
                                "targetType":"page",
                                "url":"奖励查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c6623c0b90d14285aa80eb53ad762540",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":275},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"46169b562f194bff99135419d8ab211b",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":283},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e93993fc13514a9c912c437dc0c92830",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":283},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4cde855aa6fa489baf4a24b7798940ae",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00,
                      "opacity":1},
                    "location":{
                      "x":31,
                      "y":85},
                    "size":{
                      "width":78,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d268bc0ad18046bb83fc6de9e6221947",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00,
                          "opacity":1},
                        "location":{
                          "x":31,
                          "y":85},
                        "size":{
                          "width":78,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 注册新会员",
                              "target":{
                                "targetType":"page",
                                "url":"注册新会员.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"51ee4eab80b2417fb651e78f984a02cb",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":107},
                    "size":{
                      "width":78,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"89c1784f27f24a8dbb5ed00e8edf65c0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":107},
                        "size":{
                          "width":78,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 新会员管理",
                              "target":{
                                "targetType":"page",
                                "url":"新会员管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e4c37a05917843c9ae37e3e7b8f0f8b4",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":129},
                    "size":{
                      "width":91,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3eb52831f45b43b88432c27090cc11c9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":129},
                        "size":{
                          "width":91,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 修改本人资料",
                              "target":{
                                "targetType":"page",
                                "url":"修改本人资料.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"53d38d08d2e04c7da37b12837239c739",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":150},
                    "size":{
                      "width":91,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a5ff5bf38b44ed381b6fdf1f91ef654",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":150},
                        "size":{
                          "width":91,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 修改本人密码",
                              "target":{
                                "targetType":"page",
                                "url":"修改本人密码.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"15cbe2029bf74202b5da9a1343ec4a29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":70},
            "size":{
              "width":152,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cba7682804544eabaab812417e0b8d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":70},
                "size":{
                  "width":152,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4fb5747e7d245c0a9a36c3243e5656e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":162},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d0294b1130b4e56ab35e5cbda11dfd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":162},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50e0766e9326455e8679ba65f90156c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xA5006600},
                "linePattern":"solid"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFDFEACA},
            "location":{
              "x":816,
              "y":639},
            "size":{
              "width":87,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF6DB847},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5b3cd6fb49249c0a8d2ac910ae9a938",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xA5006600},
                    "linePattern":"solid"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDFEACA},
                "location":{
                  "x":816,
                  "y":639},
                "size":{
                  "width":87,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF6DB847},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 ",
                      "objectsToFades":[]},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 注册成功",
                      "target":{
                        "targetType":"page",
                        "url":"注册成功.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/注册表单/u84.png",
            "mouseOver~":"images/注册表单/u84_mouseOver.png"}},
{
          "id":"841ed381e6b14cd3ad6cbe4393b27738",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":263,
              "y":201},
            "size":{
              "width":640,
              "height":409}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"244095aea07c4cf685f5d64b0e135198",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":263,
                  "y":201},
                "size":{
                  "width":640,
                  "height":409}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"755a9b5738924fd0a637f746fc4ce947",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xA5006600},
                "linePattern":"solid"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFDFEACA},
            "location":{
              "x":668,
              "y":639},
            "size":{
              "width":87,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF6DB847},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"893fba13b5d94f1b80f403760536fd78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xA5006600},
                    "linePattern":"solid"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDFEACA},
                "location":{
                  "x":668,
                  "y":639},
                "size":{
                  "width":87,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF6DB847},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 ",
                      "objectsToFades":[]},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 注册表单",
                      "target":{
                        "targetType":"page",
                        "url":"注册表单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/注册表单/u84.png",
            "mouseOver~":"images/注册表单/u84_mouseOver.png"}},
{
          "id":"35c94141b72f45c384badc1498e310be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":263,
              "y":367},
            "size":{
              "width":157,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d348a5768364a619837a9405af5ef6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":263,
                  "y":367},
                "size":{
                  "width":157,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5d35e04904c420bacfa35f003511171",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":263,
              "y":412},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"009a3c624ecc482f9c109e84b3cf612c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":263,
                  "y":412},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b83af5e8392e4a5ba1d639ebbefeae70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":373},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ca0ef74ace845dc8b97f62c79503755",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":373},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"764f31ca90a242feb5bf5a2ddd01198b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":263,
              "y":464},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3183b3c77118476c8db69b43b231e8db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":263,
                  "y":464},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a960725f03a64a60b7be6d1299121342",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":263,
              "y":519},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"626f203b2a644f92b0781b9fb5b996f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":263,
                  "y":519},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"975bf3e9c82c42888f87851ce03f3987",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":447},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0049acc19897450a869cae44debca670",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":464,
                  "y":447},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户管理/u245.png"}},
{
          "id":"e29e290db647431da0d1af774a6bdc4c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":447},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac383db4767745169f8ef2aa99611955",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":447},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户管理/u245.png"}},
{
          "id":"e5f1c4311ac0413582027fa0151c47f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":507},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef6c870c37414fe9943911bcdce35ee2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":464,
                  "y":507},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户管理/u245.png"}},
{
          "id":"4b67d5ef6d2949cf8f77b4ba624bbe9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":612,
              "y":185},
            "size":{
              "width":200,
              "height":165}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8040e8ad5a14f34b0e3e2b7bc3e89c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":612,
                  "y":185},
                "size":{
                  "width":200,
                  "height":165}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff511ff40a004b428513b416d73131a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":263,
              "y":201},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8dde10c53fc4a66a43c74581738d9fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":263,
                  "y":201},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d93b3c37e60f4687a0206b9c6da6971e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":306,
              "y":15},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"395c7df73f3a416c80f40a2a5f3983e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":15},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b954b91c9d2e46869b6ab0e4276e4076",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":408,
              "y":15},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a17735da222b4389934c052f68982e3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":408,
                  "y":15},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b8cc99142eb2412da362157e4938a5e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":785,
              "y":15},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdb000e03fc74a77bd1a93573cff0376",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":785,
                  "y":15},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改本人密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改本人密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c60b39a65454eaeb1ef09fcda509b44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":868,
              "y":15},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a87dec3763594bd6accf0aa87a4347b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":868,
                  "y":15},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fac4633730648a58ef417efc5f8df4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":617,
              "y":15},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"256b9412bd374d3f8aa19530ff4f1f12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":617,
                  "y":15},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66916f65c9674921bf092b0a77870a49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":15},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47e1b0a7a1a94e1992413bca321ebea3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":708,
                  "y":15},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e06fee3ac184b4fb900e6fd86b4ba25",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":737,
              "y":15},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6f9ffa164f14d7a9b5f40d49b4c6409",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":737,
                  "y":15},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u121.png"}},
{
          "id":"d77ca658a521435fa71860ebe82a8398",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":15},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c1b1d54f4974cab8723e5ed2fb57a65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":15},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f0eed6a418a04f0e9b6387f7bf3458c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":671,
              "y":15},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbf275c7133a42578db0db608dcc2e75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":671,
                  "y":15},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60d95b6346144eeca49a228051641ed8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":526,
              "y":14},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b70ae8789bd74f20b89685cc1024a591",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":526,
                  "y":14},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 购物车",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u127.png"}},
{
          "id":"dcfd3d4b5eb24a48bd30a78b11124467",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":3},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df53a81b797143c0b5f850dc98bd6412",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":542,
                  "y":3},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/系统登录默认页/u129.png"}},
{
          "id":"933746b1005445e08a365ad48cb6c584",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":547,
              "y":1},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d55119f455bb40ecb5df52c7c998823f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":547,
                  "y":1},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "d2415d04c3894ee2a19022d44e11f35b":{
      "packageId":"d2415d04c3894ee2a19022d44e11f35b",
      "type":"Axure:Master",
      "name":"nav",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7837bfaf60f741f3a6519b77012fd40a",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"7a89eecc0e584f76adbdcdcf2a6c58e7"}]}},
    "7a89eecc0e584f76adbdcdcf2a6c58e7":{
      "packageId":"7a89eecc0e584f76adbdcdcf2a6c58e7",
      "type":"Axure:Master",
      "name":"nav1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"82d5041198434b178bff196e00dfbfe6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":141,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7824ebb366034aba98ee9785a7394f11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":141,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg"}}]}}},
  "objectPaths":{
    "460aff69d326454db412d2ce1514ea7d":{
      "scriptId":"u0"},
    "1639b7318f09462d975df77e011bdabf":{
      "scriptId":"u1"},
    "2168250cea454bf598284ca131292b39":{
      "scriptId":"u2"},
    "26ee39431e494812b8f7eb29200591fd":{
      "scriptId":"u3",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u4",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u5"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u6"}}},
    "8738c122bb0b4dd8b9cfc8b7b38e1aa4":{
      "scriptId":"u7"},
    "9593b9c88fbb402d880eb0aef1d8a1d6":{
      "scriptId":"u8"},
    "ae9a22af6b044161a5d37c8a60dcb285":{
      "scriptId":"u9",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u10",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u11"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u12"}}},
    "ef85111489db42f0b199f546178a9380":{
      "scriptId":"u13"},
    "540aa35d3a114afa9f9ecd8bac382116":{
      "scriptId":"u14"},
    "06db65c496254602ae8cdc8e6ba4ebf1":{
      "scriptId":"u15",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u16",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u17"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u18"}}},
    "3f130c4faa5d4162b587e622fa660bcc":{
      "scriptId":"u19"},
    "5564cb085e4a44cb8645ea18e70d45de":{
      "scriptId":"u20"},
    "efbde381c9b44cc999e27d003ff04553":{
      "scriptId":"u21",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u22",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u23"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u24"}}},
    "63472a5695ee4506847c7035bc3de05f":{
      "scriptId":"u25"},
    "983379fdf753407a8e5f2f72535f853b":{
      "scriptId":"u26"},
    "e32942c026e7497fbe38cf8487aa0629":{
      "scriptId":"u27",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u28",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u29"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u30"}}},
    "96530caba9e54ac789c8c1f45fb6caa1":{
      "scriptId":"u31"},
    "a48922b90d7d4e12a393b824206712cf":{
      "scriptId":"u32"},
    "c6623c0b90d14285aa80eb53ad762540":{
      "scriptId":"u33",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u34",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u35"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u36"}}},
    "46169b562f194bff99135419d8ab211b":{
      "scriptId":"u37"},
    "e93993fc13514a9c912c437dc0c92830":{
      "scriptId":"u38"},
    "4cde855aa6fa489baf4a24b7798940ae":{
      "scriptId":"u39"},
    "d268bc0ad18046bb83fc6de9e6221947":{
      "scriptId":"u40"},
    "51ee4eab80b2417fb651e78f984a02cb":{
      "scriptId":"u41"},
    "89c1784f27f24a8dbb5ed00e8edf65c0":{
      "scriptId":"u42"},
    "e4c37a05917843c9ae37e3e7b8f0f8b4":{
      "scriptId":"u43"},
    "3eb52831f45b43b88432c27090cc11c9":{
      "scriptId":"u44"},
    "53d38d08d2e04c7da37b12837239c739":{
      "scriptId":"u45"},
    "6a5ff5bf38b44ed381b6fdf1f91ef654":{
      "scriptId":"u46"},
    "15cbe2029bf74202b5da9a1343ec4a29":{
      "scriptId":"u47"},
    "6cba7682804544eabaab812417e0b8d6":{
      "scriptId":"u48"},
    "c4fb5747e7d245c0a9a36c3243e5656e":{
      "scriptId":"u49"},
    "8d0294b1130b4e56ab35e5cbda11dfd6":{
      "scriptId":"u50"},
    "50e0766e9326455e8679ba65f90156c8":{
      "scriptId":"u51"},
    "b5b3cd6fb49249c0a8d2ac910ae9a938":{
      "scriptId":"u52"},
    "841ed381e6b14cd3ad6cbe4393b27738":{
      "scriptId":"u53"},
    "244095aea07c4cf685f5d64b0e135198":{
      "scriptId":"u54"},
    "755a9b5738924fd0a637f746fc4ce947":{
      "scriptId":"u55"},
    "893fba13b5d94f1b80f403760536fd78":{
      "scriptId":"u56"},
    "35c94141b72f45c384badc1498e310be":{
      "scriptId":"u57"},
    "4d348a5768364a619837a9405af5ef6e":{
      "scriptId":"u58"},
    "e5d35e04904c420bacfa35f003511171":{
      "scriptId":"u59"},
    "009a3c624ecc482f9c109e84b3cf612c":{
      "scriptId":"u60"},
    "b83af5e8392e4a5ba1d639ebbefeae70":{
      "scriptId":"u61"},
    "2ca0ef74ace845dc8b97f62c79503755":{
      "scriptId":"u62"},
    "764f31ca90a242feb5bf5a2ddd01198b":{
      "scriptId":"u63"},
    "3183b3c77118476c8db69b43b231e8db":{
      "scriptId":"u64"},
    "a960725f03a64a60b7be6d1299121342":{
      "scriptId":"u65"},
    "626f203b2a644f92b0781b9fb5b996f8":{
      "scriptId":"u66"},
    "975bf3e9c82c42888f87851ce03f3987":{
      "scriptId":"u67"},
    "0049acc19897450a869cae44debca670":{
      "scriptId":"u68"},
    "e29e290db647431da0d1af774a6bdc4c":{
      "scriptId":"u69"},
    "ac383db4767745169f8ef2aa99611955":{
      "scriptId":"u70"},
    "e5f1c4311ac0413582027fa0151c47f8":{
      "scriptId":"u71"},
    "ef6c870c37414fe9943911bcdce35ee2":{
      "scriptId":"u72"},
    "4b67d5ef6d2949cf8f77b4ba624bbe9d":{
      "scriptId":"u73"},
    "a8040e8ad5a14f34b0e3e2b7bc3e89c2":{
      "scriptId":"u74"},
    "ff511ff40a004b428513b416d73131a8":{
      "scriptId":"u75"},
    "c8dde10c53fc4a66a43c74581738d9fe":{
      "scriptId":"u76"},
    "d93b3c37e60f4687a0206b9c6da6971e":{
      "scriptId":"u77"},
    "395c7df73f3a416c80f40a2a5f3983e1":{
      "scriptId":"u78"},
    "b954b91c9d2e46869b6ab0e4276e4076":{
      "scriptId":"u79"},
    "a17735da222b4389934c052f68982e3b":{
      "scriptId":"u80"},
    "b8cc99142eb2412da362157e4938a5e2":{
      "scriptId":"u81"},
    "bdb000e03fc74a77bd1a93573cff0376":{
      "scriptId":"u82"},
    "3c60b39a65454eaeb1ef09fcda509b44":{
      "scriptId":"u83"},
    "a87dec3763594bd6accf0aa87a4347b8":{
      "scriptId":"u84"},
    "6fac4633730648a58ef417efc5f8df4b":{
      "scriptId":"u85"},
    "256b9412bd374d3f8aa19530ff4f1f12":{
      "scriptId":"u86"},
    "66916f65c9674921bf092b0a77870a49":{
      "scriptId":"u87"},
    "47e1b0a7a1a94e1992413bca321ebea3":{
      "scriptId":"u88"},
    "3e06fee3ac184b4fb900e6fd86b4ba25":{
      "scriptId":"u89"},
    "f6f9ffa164f14d7a9b5f40d49b4c6409":{
      "scriptId":"u90"},
    "d77ca658a521435fa71860ebe82a8398":{
      "scriptId":"u91"},
    "8c1b1d54f4974cab8723e5ed2fb57a65":{
      "scriptId":"u92"},
    "f0eed6a418a04f0e9b6387f7bf3458c9":{
      "scriptId":"u93"},
    "fbf275c7133a42578db0db608dcc2e75":{
      "scriptId":"u94"},
    "60d95b6346144eeca49a228051641ed8":{
      "scriptId":"u95"},
    "b70ae8789bd74f20b89685cc1024a591":{
      "scriptId":"u96"},
    "dcfd3d4b5eb24a48bd30a78b11124467":{
      "scriptId":"u97"},
    "df53a81b797143c0b5f850dc98bd6412":{
      "scriptId":"u98"},
    "933746b1005445e08a365ad48cb6c584":{
      "scriptId":"u99"},
    "d55119f455bb40ecb5df52c7c998823f":{
      "scriptId":"u100"}}});