$axure.loadCurrentPage({
  "url":"推荐查询.html",
  "generationDate":new Date(1383038968228.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/系统登录默认页/bg.jpg",
    "width":1000,
    "height":750},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"7c6ef876a1fb46c583c0ed75db7789ca",
    "type":"Axure:Page",
    "name":"推荐查询",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3fb658a83ec148b4bab64d57fcabe6b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":160},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"705b10b366fe4296af0fe5d6523f6f71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":160},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4fed4824be514be3a622224dd31b70f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":338,
              "y":160},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe07d6ba4947488c8067c5f949ad4795",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":338,
                  "y":160},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e1da9a3138a4c0bbecd5c2ead322050",
          "label":"菜单",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":170},
            "size":{
              "width":141,
              "height":520}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"0bc32e26a42c4837872c701f5a76503b",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"277972b209ba43c1acf68a578d1c3266",
                  "label":"",
                  "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":10}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"de50522509ef4d298d9b1cff930f8136",
                  "label":"",
                  "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":18},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4cf33b4b8b39452682ee378f681fbae2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":18},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b01f13e22a0e47e7b6a38d84adc1f8d8",
                  "label":"",
                  "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":43}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"eecd52a96ab845d3ae09401a78508d7b",
                  "label":"",
                  "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":51},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"faac44ed233f45c8bbae05483000acbe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":51},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 注册新会员",
                              "target":{
                                "targetType":"page",
                                "url":"注册新会员.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"29e235ce56e04de0baf18b21f5ae966b",
                  "label":"",
                  "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":76},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"493fc024b90c45e19ee8cac9fd7a2927",
                  "label":"",
                  "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":84},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"abfd85129f4d43b291a43540ade59d5b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":84},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 提现明细",
                              "target":{
                                "targetType":"page",
                                "url":"提现明细.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"006aaf93640747119716949b7a73793c",
                  "label":"",
                  "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":109},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"94a43b914d544da08ec677b63e259875",
                  "label":"",
                  "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":117},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"99cfb8a167bd4209a2d71438abb9fb8f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":117},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 报单购物",
                              "target":{
                                "targetType":"page",
                                "url":"报单购物.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1686cf4510be42eca2270f35ee27957c",
                  "label":"",
                  "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":142},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"e93005c99b8e455eaad949d29d2fa761",
                  "label":"",
                  "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":150},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5ff17d307da645c28a4f71999258c1ef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":150},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 奖励查询",
                              "target":{
                                "targetType":"page",
                                "url":"奖励查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2ed703906f294b089eda25b8a80d7685",
                  "label":"",
                  "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":279},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"27085a1cea6d48fc9a708d6000cb08aa",
                  "label":"",
                  "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":287},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"35f9a1299d87422382122f7bbede123d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":287},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e7381d5db4eb4fdfb8248e43ebe832d1",
                  "label":"",
                  "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":31,
                      "y":184},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"700327b5be094ce48a82a148056bae2f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":31,
                          "y":184},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 奖励查询",
                              "target":{
                                "targetType":"page",
                                "url":"奖励查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0a1ea8d3c3574d61bcc9cff86442d88f",
                  "label":"",
                  "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":208},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1b7f38f466264e8e99b0615e99079d11",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":208},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 推荐查询",
                              "target":{
                                "targetType":"page",
                                "url":"推荐查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1e7c7893e95548078b964c816e154dab",
                  "label":"",
                  "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":231},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"83da9376c25346db9a5338bf16ab675c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":231},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 区域查询",
                              "target":{
                                "targetType":"page",
                                "url":"区域查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"48bf721631864416bbd65336f15e29e9",
                  "label":"",
                  "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":253},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"62c9d20d4e82438280e28c62da37160b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e1da9a3138a4c0bbecd5c2ead322050",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":253},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 操作须知",
                              "target":{
                                "targetType":"page",
                                "url":"操作须知.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"3221676dcb8245adabfe13a08997d451",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":230},
            "size":{
              "width":182,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb1a3e886d6f43ef8ef278770c924276",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "size":{
                  "width":149,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"72cb06f1bd6d4253bbfca907c6563122",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":149,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"73be63f5602545c9a00e2f482e425e63",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":149,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e637d675c93645d5a04b6916ce86d140",
                  "label":"1",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "stateStyles":null,
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":162,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b6068ab595c54fdf96e49158968aa50b",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "stateStyles":null,
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":162,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"6e3a9b5aa0b64d04ad26d44bcc1ad44e",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":null,
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFE4E4E4},
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":162,
                              "height":20},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFE4E4E4}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/推荐查询/u56.png"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 man2",
                              "objectsToFades":[{
                                  "objectPath":["3e2a7fbd037e47ea88c4670571615e84"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示 man1",
                              "objectsToFades":[{
                                  "objectPath":["20119475a4574b7986cbdca8b91ddc20"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"b6068ab595c54fdf96e49158968aa50b"},
{
                  "id":"245763e5f47b4a308ea8e2ad6f8ef744",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"40a8518256fd4ffea2e5b50ad2338e9c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/推荐查询/u51.png",
                    "selected~":"images/推荐查询/u51_selected.png"}},
{
                  "id":"934524f31b14453582a0240c80cf8c15",
                  "label":"2",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "stateStyles":null,
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":157,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9122e816777f467d80f2935dbf5d22a3",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "stateStyles":null,
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":157,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ead8844911664491957fe647c5901118",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":null,
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":157,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 man1",
                              "objectsToFades":[{
                                  "objectPath":["20119475a4574b7986cbdca8b91ddc20"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示 man2",
                              "objectsToFades":[{
                                  "objectPath":["3e2a7fbd037e47ea88c4670571615e84"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"9122e816777f467d80f2935dbf5d22a3"},
{
                  "id":"3f5af647bb814124bea008ddd3edb3c1",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "stateStyles":null,
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":149,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d50d476ef7564f35a5945a59ac0524cd",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "stateStyles":null,
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":149,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"2f97d82ca0b642c5bae97aab372d00a8",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "stateStyles":null,
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":149,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"d50d476ef7564f35a5945a59ac0524cd"}],
              "buttonShapeId":"72cb06f1bd6d4253bbfca907c6563122"}]},
{
          "id":"7b8c4d951ae74d86b368521e821f8892",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":461,
              "y":200},
            "size":{
              "width":10,
              "height":470},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/推荐查询/u64_line.png"}},
{
          "id":"20119475a4574b7986cbdca8b91ddc20",
          "label":"man1",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":233},
            "size":{
              "width":430,
              "height":387}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3f156b347384567b912f5c55b04f269",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":233},
                "size":{
                  "width":430,
                  "height":387}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"079969f433d64b10bd0659a6a044f920",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":500,
              "y":207},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d023dd1da4bf4ab8bc817c0e59756ee0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":500,
                  "y":207},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b224783149254cc0af7970156e536823",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":260,
              "y":202},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c8d4b06ae8e487182d509e955ad0995",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":260,
                  "y":202},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93a38922f2104ee693e59859e3c64dad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":477,
              "y":207},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cacac4c369fa46d7a0ffbcc21e56f7f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":477,
                  "y":207},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户管理/u343.png"}},
{
          "id":"5a5dcd2f3c6d4dcd95b8fdbdcc076c8d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":242,
              "y":202},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"413934ad53c04d59b1e27a2cee78bc36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":242,
                  "y":202},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/推荐查询/u73.png"}},
{
          "id":"3e2a7fbd037e47ea88c4670571615e84",
          "label":"man2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":false,
          "style":{
            "location":{
              "x":500,
              "y":233},
            "size":{
              "width":430,
              "height":387},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ce13af5296c454ea0d36b5fd5c8b840",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":500,
                  "y":233},
                "size":{
                  "width":430,
                  "height":387},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e1f0bc0b3d14dfdbd2c7ea4e67e0e14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":284,
              "y":578},
            "size":{
              "width":174,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4380fd87ff07498585a5a4c0a169bded",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":284,
                  "y":578},
                "size":{
                  "width":174,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abb8fa8898fc42269d815424dcad298a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":84},
            "size":{
              "width":160,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bfaf8be9c4a49d2b315b79840e4d689",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":84},
                "size":{
                  "width":160,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3673383612b4d758a612bc8e7314ce1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":306,
              "y":15},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1396f24351864a01b31b6476efde9725",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":15},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3e6239f56ba46a29e186e3a76213dd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":408,
              "y":15},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e8a5f0fb24b4821bf25e86322f15228",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":408,
                  "y":15},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83ce045f3a0c415a984c49ca3bdde82a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":785,
              "y":15},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f74d880ce1ee4852b10ba13efd46252e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":785,
                  "y":15},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改本人密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改本人密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc8e206e264c486eb9d6db5fdf00c67e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":868,
              "y":15},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b72fdc62373b40baab0cfb5e24e91504",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":868,
                  "y":15},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b73e101c6ed42bebf07df0bfe876e9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":617,
              "y":15},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb5cb93e80724b19af6d5e2214ff01a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":617,
                  "y":15},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fd2c98b38e5495194bf0f780edb0c29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":15},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b970b0467524ae3b3b61ac4f450241e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":708,
                  "y":15},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d21c530a88043feae7331f4016f108f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":737,
              "y":15},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7449f7a483a48a38b9caf103209bd04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":737,
                  "y":15},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u121.png"}},
{
          "id":"2cd1796f468f40b881fdfda859eb2d5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":15},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be3df432df9248b8a2f6100139a08d64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":15},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0cc4e36e96814b3ebfa83a28e79b232a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":671,
              "y":15},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bb3e06468304384ae204c4c5beefa02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":671,
                  "y":15},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66e7accf4be9451d84c8dcf62e44af80",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":526,
              "y":14},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"512f04e6897246199ecc36b9f700c9c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":526,
                  "y":14},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 购物车",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u127.png"}},
{
          "id":"264fdf677fe041ac816842a825b1a255",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":3},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cf8d7ad765e4c73aba78d6eba3c5042",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":542,
                  "y":3},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/系统登录默认页/u129.png"}},
{
          "id":"304b7c9ecc284e6daeddd2de4978360b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":547,
              "y":1},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b28d34fec00427eaf7cf02a027ab03c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":547,
                  "y":1},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "d2415d04c3894ee2a19022d44e11f35b":{
      "packageId":"d2415d04c3894ee2a19022d44e11f35b",
      "type":"Axure:Master",
      "name":"nav",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7837bfaf60f741f3a6519b77012fd40a",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"7a89eecc0e584f76adbdcdcf2a6c58e7"}]}},
    "7a89eecc0e584f76adbdcdcf2a6c58e7":{
      "packageId":"7a89eecc0e584f76adbdcdcf2a6c58e7",
      "type":"Axure:Master",
      "name":"nav1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"82d5041198434b178bff196e00dfbfe6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":141,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7824ebb366034aba98ee9785a7394f11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":141,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg"}}]}}},
  "objectPaths":{
    "3fb658a83ec148b4bab64d57fcabe6b6":{
      "scriptId":"u0"},
    "705b10b366fe4296af0fe5d6523f6f71":{
      "scriptId":"u1"},
    "4fed4824be514be3a622224dd31b70f5":{
      "scriptId":"u2"},
    "fe07d6ba4947488c8067c5f949ad4795":{
      "scriptId":"u3"},
    "1e1da9a3138a4c0bbecd5c2ead322050":{
      "scriptId":"u4"},
    "277972b209ba43c1acf68a578d1c3266":{
      "scriptId":"u5",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u6",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u7"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u8"}}},
    "de50522509ef4d298d9b1cff930f8136":{
      "scriptId":"u9"},
    "4cf33b4b8b39452682ee378f681fbae2":{
      "scriptId":"u10"},
    "b01f13e22a0e47e7b6a38d84adc1f8d8":{
      "scriptId":"u11",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u12",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u13"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u14"}}},
    "eecd52a96ab845d3ae09401a78508d7b":{
      "scriptId":"u15"},
    "faac44ed233f45c8bbae05483000acbe":{
      "scriptId":"u16"},
    "29e235ce56e04de0baf18b21f5ae966b":{
      "scriptId":"u17",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u18",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u19"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u20"}}},
    "493fc024b90c45e19ee8cac9fd7a2927":{
      "scriptId":"u21"},
    "abfd85129f4d43b291a43540ade59d5b":{
      "scriptId":"u22"},
    "006aaf93640747119716949b7a73793c":{
      "scriptId":"u23",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u24",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u25"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u26"}}},
    "94a43b914d544da08ec677b63e259875":{
      "scriptId":"u27"},
    "99cfb8a167bd4209a2d71438abb9fb8f":{
      "scriptId":"u28"},
    "1686cf4510be42eca2270f35ee27957c":{
      "scriptId":"u29",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u30",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u31"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u32"}}},
    "e93005c99b8e455eaad949d29d2fa761":{
      "scriptId":"u33"},
    "5ff17d307da645c28a4f71999258c1ef":{
      "scriptId":"u34"},
    "2ed703906f294b089eda25b8a80d7685":{
      "scriptId":"u35",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u36",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u37"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u38"}}},
    "27085a1cea6d48fc9a708d6000cb08aa":{
      "scriptId":"u39"},
    "35f9a1299d87422382122f7bbede123d":{
      "scriptId":"u40"},
    "e7381d5db4eb4fdfb8248e43ebe832d1":{
      "scriptId":"u41"},
    "700327b5be094ce48a82a148056bae2f":{
      "scriptId":"u42"},
    "0a1ea8d3c3574d61bcc9cff86442d88f":{
      "scriptId":"u43"},
    "1b7f38f466264e8e99b0615e99079d11":{
      "scriptId":"u44"},
    "1e7c7893e95548078b964c816e154dab":{
      "scriptId":"u45"},
    "83da9376c25346db9a5338bf16ab675c":{
      "scriptId":"u46"},
    "48bf721631864416bbd65336f15e29e9":{
      "scriptId":"u47"},
    "62c9d20d4e82438280e28c62da37160b":{
      "scriptId":"u48"},
    "3221676dcb8245adabfe13a08997d451":{
      "scriptId":"u49"},
    "fb1a3e886d6f43ef8ef278770c924276":{
      "scriptId":"u50"},
    "245763e5f47b4a308ea8e2ad6f8ef744":{
      "scriptId":"u51"},
    "40a8518256fd4ffea2e5b50ad2338e9c":{
      "scriptId":"u52"},
    "72cb06f1bd6d4253bbfca907c6563122":{
      "scriptId":"u53"},
    "73be63f5602545c9a00e2f482e425e63":{
      "scriptId":"u54"},
    "e637d675c93645d5a04b6916ce86d140":{
      "scriptId":"u55"},
    "b6068ab595c54fdf96e49158968aa50b":{
      "scriptId":"u56"},
    "6e3a9b5aa0b64d04ad26d44bcc1ad44e":{
      "scriptId":"u57"},
    "934524f31b14453582a0240c80cf8c15":{
      "scriptId":"u58"},
    "9122e816777f467d80f2935dbf5d22a3":{
      "scriptId":"u59"},
    "ead8844911664491957fe647c5901118":{
      "scriptId":"u60"},
    "3f5af647bb814124bea008ddd3edb3c1":{
      "scriptId":"u61"},
    "d50d476ef7564f35a5945a59ac0524cd":{
      "scriptId":"u62"},
    "2f97d82ca0b642c5bae97aab372d00a8":{
      "scriptId":"u63"},
    "7b8c4d951ae74d86b368521e821f8892":{
      "scriptId":"u64"},
    "20119475a4574b7986cbdca8b91ddc20":{
      "scriptId":"u65"},
    "e3f156b347384567b912f5c55b04f269":{
      "scriptId":"u66"},
    "079969f433d64b10bd0659a6a044f920":{
      "scriptId":"u67"},
    "d023dd1da4bf4ab8bc817c0e59756ee0":{
      "scriptId":"u68"},
    "b224783149254cc0af7970156e536823":{
      "scriptId":"u69"},
    "1c8d4b06ae8e487182d509e955ad0995":{
      "scriptId":"u70"},
    "93a38922f2104ee693e59859e3c64dad":{
      "scriptId":"u71"},
    "cacac4c369fa46d7a0ffbcc21e56f7f2":{
      "scriptId":"u72"},
    "5a5dcd2f3c6d4dcd95b8fdbdcc076c8d":{
      "scriptId":"u73"},
    "413934ad53c04d59b1e27a2cee78bc36":{
      "scriptId":"u74"},
    "3e2a7fbd037e47ea88c4670571615e84":{
      "scriptId":"u75"},
    "0ce13af5296c454ea0d36b5fd5c8b840":{
      "scriptId":"u76"},
    "9e1f0bc0b3d14dfdbd2c7ea4e67e0e14":{
      "scriptId":"u77"},
    "4380fd87ff07498585a5a4c0a169bded":{
      "scriptId":"u78"},
    "abb8fa8898fc42269d815424dcad298a":{
      "scriptId":"u79"},
    "3bfaf8be9c4a49d2b315b79840e4d689":{
      "scriptId":"u80"},
    "e3673383612b4d758a612bc8e7314ce1":{
      "scriptId":"u81"},
    "1396f24351864a01b31b6476efde9725":{
      "scriptId":"u82"},
    "b3e6239f56ba46a29e186e3a76213dd9":{
      "scriptId":"u83"},
    "3e8a5f0fb24b4821bf25e86322f15228":{
      "scriptId":"u84"},
    "83ce045f3a0c415a984c49ca3bdde82a":{
      "scriptId":"u85"},
    "f74d880ce1ee4852b10ba13efd46252e":{
      "scriptId":"u86"},
    "fc8e206e264c486eb9d6db5fdf00c67e":{
      "scriptId":"u87"},
    "b72fdc62373b40baab0cfb5e24e91504":{
      "scriptId":"u88"},
    "8b73e101c6ed42bebf07df0bfe876e9c":{
      "scriptId":"u89"},
    "cb5cb93e80724b19af6d5e2214ff01a3":{
      "scriptId":"u90"},
    "7fd2c98b38e5495194bf0f780edb0c29":{
      "scriptId":"u91"},
    "7b970b0467524ae3b3b61ac4f450241e":{
      "scriptId":"u92"},
    "7d21c530a88043feae7331f4016f108f":{
      "scriptId":"u93"},
    "c7449f7a483a48a38b9caf103209bd04":{
      "scriptId":"u94"},
    "2cd1796f468f40b881fdfda859eb2d5f":{
      "scriptId":"u95"},
    "be3df432df9248b8a2f6100139a08d64":{
      "scriptId":"u96"},
    "0cc4e36e96814b3ebfa83a28e79b232a":{
      "scriptId":"u97"},
    "9bb3e06468304384ae204c4c5beefa02":{
      "scriptId":"u98"},
    "66e7accf4be9451d84c8dcf62e44af80":{
      "scriptId":"u99"},
    "512f04e6897246199ecc36b9f700c9c2":{
      "scriptId":"u100"},
    "264fdf677fe041ac816842a825b1a255":{
      "scriptId":"u101"},
    "0cf8d7ad765e4c73aba78d6eba3c5042":{
      "scriptId":"u102"},
    "304b7c9ecc284e6daeddd2de4978360b":{
      "scriptId":"u103"},
    "9b28d34fec00427eaf7cf02a027ab03c":{
      "scriptId":"u104"}}});