$axure.loadCurrentPage({
  "url":"公告详细页面_1.html",
  "generationDate":new Date(1383038971007.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/系统登录默认页/bg.jpg",
    "width":1000,
    "height":750},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"41d00bb3a4fd435aa19b6042982f31aa",
    "type":"Axure:Page",
    "name":"公告详细页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"985c187c7cc747fa85a70be667b9ffc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":162},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a977dba06b4848f8b9e68c1457154e4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":162},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 公告管理",
                      "target":{
                        "targetType":"page",
                        "url":"公告管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"346707c2d91544c386b74ff811008b15",
          "label":"菜单",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":170},
            "size":{
              "width":141,
              "height":520}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"d27733f6f81249e9a78296651ceb2775",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"074b08008a3c499d92d3af712182945d",
                  "label":"",
                  "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":10}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"3a15efda2b834ab2bb3b280f990d6d06",
                  "label":"",
                  "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":18},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"89075e3553d84f31ae5d162e08713a0e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":18},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"11789b7a443d44dfafe7d92bbf8e3661",
                  "label":"",
                  "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":43},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"1e4994cfeb2d44a0993f85541249fa91",
                  "label":"",
                  "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":51},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ade738d9a2764a1d9397b40573487ad9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":51},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 注册新会员",
                              "target":{
                                "targetType":"page",
                                "url":"注册新会员.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"db14581b0cd84d188944bc104e945d64",
                  "label":"",
                  "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":76},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"07d1edbbd9cf436992b86d966393c583",
                  "label":"",
                  "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":84},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cb4147eb02664fbf941f39cbca6e78ba",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":84},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 汇款充值",
                              "target":{
                                "targetType":"page",
                                "url":"汇款充值.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3ef3d6e4c86d41ceab15415fa7b60d7f",
                  "label":"",
                  "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":109},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"80fe609a754f4be384c6a66b3db6e427",
                  "label":"",
                  "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":117},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a42358b86b8247f2afa5d871dcb8bb27",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":117},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 报单购物",
                              "target":{
                                "targetType":"page",
                                "url":"报单购物.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"424f7c3d0549413385e6946e2ed777b2",
                  "label":"",
                  "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":142},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"ec797b5fb62b464e98ea0d8ce486bf5e",
                  "label":"",
                  "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":150},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"67a12e1b2540465a93513428c1170af7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":150},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 奖励查询",
                              "target":{
                                "targetType":"page",
                                "url":"奖励查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6dc3e008228a48cdb89e7db205aec060",
                  "label":"",
                  "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":175},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"c9906fd99a5a41fca6bbb852c3d0e698",
                  "label":"",
                  "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":183},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"63a923d305794b4abb317a9673a675b7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":183},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6d7fd5dbeb354a8aa87a2130485292c6",
                  "label":"",
                  "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00,
                      "opacity":1},
                    "location":{
                      "x":26,
                      "y":217},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c60b05a100db4f509d8ed1a06b2937bf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00,
                          "opacity":1},
                        "location":{
                          "x":26,
                          "y":217},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"20a142520cd7449ab832a78d217d01e3",
                  "label":"",
                  "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":26,
                      "y":241},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"263cad62b88f424d8678d9878bf182a2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":26,
                          "y":241},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 资讯管理",
                              "target":{
                                "targetType":"page",
                                "url":"资讯管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bc6d8c25ae7d42258be3f5cbb5bdbc4e",
                  "label":"",
                  "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":26,
                      "y":267},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5b360c8f688e4f2090892e16e1d6a72c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":26,
                          "y":267},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 下载中心",
                              "target":{
                                "targetType":"page",
                                "url":"下载中心.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2d17cbea4acf4cd29c5e029549ae5f83",
                  "label":"",
                  "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":26,
                      "y":290},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"444bd00f051c4919a6325a24f410c22b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"346707c2d91544c386b74ff811008b15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":26,
                          "y":290},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 留言管理",
                              "target":{
                                "targetType":"page",
                                "url":"留言管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"990736d15aa3426fb4202544383e3a37",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":162},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c358a875e1ff4a47a985642551e7e93c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":162},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad9a178eef9f41908a4e4d91cce55d7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":70},
            "size":{
              "width":152,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7295e61052fc440a897e89488539f4d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":70},
                "size":{
                  "width":152,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf7ae7ffed6f4799960bd11a5b7b941f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":448,
              "y":200},
            "size":{
              "width":155,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8eea347f36974cc59a7e8c45bde9469e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":448,
                  "y":200},
                "size":{
                  "width":155,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a23d080dbf434f5095c480783fad370c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":505,
              "y":226},
            "size":{
              "width":65,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91bc30ad3dae43cd88e4aa545736726f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":505,
                  "y":226},
                "size":{
                  "width":65,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b5ffdbcb3024c1782135a2778baa662",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":240},
            "size":{
              "width":650,
              "height":416}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acfc34b3832f4719bee788bba6c574e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":240},
                "size":{
                  "width":650,
                  "height":416}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8cc3a3d9e7014f72ac929654e5071eb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xA5006600},
                "linePattern":"solid"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFDFEACA},
            "location":{
              "x":261,
              "y":626},
            "size":{
              "width":70,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF6DB847},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdc7b4c4b7574b59bf3a566a631f502c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xA5006600},
                    "linePattern":"solid"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDFEACA},
                "location":{
                  "x":261,
                  "y":626},
                "size":{
                  "width":70,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF6DB847},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 公告管理",
                      "target":{
                        "targetType":"page",
                        "url":"公告管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/公告详细页面/u57.png",
            "mouseOver~":"images/公告详细页面/u57_mouseOver.png"}},
{
          "id":"fa0ca09fe4af448497f51dc8b77199fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":306,
              "y":15},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5b81ece76344e978499482aad657320",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":15},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c8b598838f840fdb27e536250504a74",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":408,
              "y":15},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bcbb5c1542b4622b918805dcced7c18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":408,
                  "y":15},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56fb6e0703c547dab305edd8e80cf43d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":785,
              "y":15},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ec0e3189d8f4ed0ab4c779e3310f5f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":785,
                  "y":15},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改本人密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改本人密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d143d29690804761a9e07c75e61838ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":868,
              "y":15},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6404148a1eac49389f155105faa05fb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":868,
                  "y":15},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"738715c91ec042f4ac990eab9c2ec028",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":617,
              "y":15},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebfd5976cc684b59927182b9b13ab964",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":617,
                  "y":15},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0bd81c4332a4d02b18a0e0238c438c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":15},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c51bdf58157e456fade324f4ace8d5da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":708,
                  "y":15},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3c4de28cc5f42c8bd027e54fff2d0d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":737,
              "y":15},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a87b6b42ad74af094024ad0ec9ae9f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":737,
                  "y":15},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u121.png"}},
{
          "id":"7db403111d1f4d5092f51b91758313c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":15},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2cd753e21ad4b47b6030a0b24bfa0f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":15},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4dc040c10cd042098b46c2e91c99e542",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":671,
              "y":15},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94288fa6f6b34896b28e5a10bce0543e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":671,
                  "y":15},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38330ef6df6d47c782a62dbf2d4f7bd7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":526,
              "y":14},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"695176f5e3cd48559f6dccf8bc879a51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":526,
                  "y":14},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 购物车",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u127.png"}},
{
          "id":"39f3d5f77c1a4c68a61f052925d228f9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":3},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"886104b76c4d4eb8bd9569a256f591ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":542,
                  "y":3},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/系统登录默认页/u129.png"}},
{
          "id":"eee9ea7fa05c4b77bd4f22c30071f39c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":547,
              "y":1},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02b686f023aa417b95c7ceb4273f4e61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":547,
                  "y":1},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "d2415d04c3894ee2a19022d44e11f35b":{
      "packageId":"d2415d04c3894ee2a19022d44e11f35b",
      "type":"Axure:Master",
      "name":"nav",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7837bfaf60f741f3a6519b77012fd40a",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"7a89eecc0e584f76adbdcdcf2a6c58e7"}]}},
    "7a89eecc0e584f76adbdcdcf2a6c58e7":{
      "packageId":"7a89eecc0e584f76adbdcdcf2a6c58e7",
      "type":"Axure:Master",
      "name":"nav1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"82d5041198434b178bff196e00dfbfe6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":141,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7824ebb366034aba98ee9785a7394f11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":141,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg"}}]}}},
  "objectPaths":{
    "985c187c7cc747fa85a70be667b9ffc9":{
      "scriptId":"u0"},
    "a977dba06b4848f8b9e68c1457154e4e":{
      "scriptId":"u1"},
    "346707c2d91544c386b74ff811008b15":{
      "scriptId":"u2"},
    "074b08008a3c499d92d3af712182945d":{
      "scriptId":"u3",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u4",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u5"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u6"}}},
    "3a15efda2b834ab2bb3b280f990d6d06":{
      "scriptId":"u7"},
    "89075e3553d84f31ae5d162e08713a0e":{
      "scriptId":"u8"},
    "11789b7a443d44dfafe7d92bbf8e3661":{
      "scriptId":"u9",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u10",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u11"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u12"}}},
    "1e4994cfeb2d44a0993f85541249fa91":{
      "scriptId":"u13"},
    "ade738d9a2764a1d9397b40573487ad9":{
      "scriptId":"u14"},
    "db14581b0cd84d188944bc104e945d64":{
      "scriptId":"u15",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u16",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u17"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u18"}}},
    "07d1edbbd9cf436992b86d966393c583":{
      "scriptId":"u19"},
    "cb4147eb02664fbf941f39cbca6e78ba":{
      "scriptId":"u20"},
    "3ef3d6e4c86d41ceab15415fa7b60d7f":{
      "scriptId":"u21",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u22",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u23"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u24"}}},
    "80fe609a754f4be384c6a66b3db6e427":{
      "scriptId":"u25"},
    "a42358b86b8247f2afa5d871dcb8bb27":{
      "scriptId":"u26"},
    "424f7c3d0549413385e6946e2ed777b2":{
      "scriptId":"u27",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u28",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u29"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u30"}}},
    "ec797b5fb62b464e98ea0d8ce486bf5e":{
      "scriptId":"u31"},
    "67a12e1b2540465a93513428c1170af7":{
      "scriptId":"u32"},
    "6dc3e008228a48cdb89e7db205aec060":{
      "scriptId":"u33",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u34",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u35"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u36"}}},
    "c9906fd99a5a41fca6bbb852c3d0e698":{
      "scriptId":"u37"},
    "63a923d305794b4abb317a9673a675b7":{
      "scriptId":"u38"},
    "6d7fd5dbeb354a8aa87a2130485292c6":{
      "scriptId":"u39"},
    "c60b05a100db4f509d8ed1a06b2937bf":{
      "scriptId":"u40"},
    "20a142520cd7449ab832a78d217d01e3":{
      "scriptId":"u41"},
    "263cad62b88f424d8678d9878bf182a2":{
      "scriptId":"u42"},
    "bc6d8c25ae7d42258be3f5cbb5bdbc4e":{
      "scriptId":"u43"},
    "5b360c8f688e4f2090892e16e1d6a72c":{
      "scriptId":"u44"},
    "2d17cbea4acf4cd29c5e029549ae5f83":{
      "scriptId":"u45"},
    "444bd00f051c4919a6325a24f410c22b":{
      "scriptId":"u46"},
    "990736d15aa3426fb4202544383e3a37":{
      "scriptId":"u47"},
    "c358a875e1ff4a47a985642551e7e93c":{
      "scriptId":"u48"},
    "ad9a178eef9f41908a4e4d91cce55d7d":{
      "scriptId":"u49"},
    "7295e61052fc440a897e89488539f4d4":{
      "scriptId":"u50"},
    "bf7ae7ffed6f4799960bd11a5b7b941f":{
      "scriptId":"u51"},
    "8eea347f36974cc59a7e8c45bde9469e":{
      "scriptId":"u52"},
    "a23d080dbf434f5095c480783fad370c":{
      "scriptId":"u53"},
    "91bc30ad3dae43cd88e4aa545736726f":{
      "scriptId":"u54"},
    "1b5ffdbcb3024c1782135a2778baa662":{
      "scriptId":"u55"},
    "acfc34b3832f4719bee788bba6c574e1":{
      "scriptId":"u56"},
    "8cc3a3d9e7014f72ac929654e5071eb6":{
      "scriptId":"u57"},
    "cdc7b4c4b7574b59bf3a566a631f502c":{
      "scriptId":"u58"},
    "fa0ca09fe4af448497f51dc8b77199fc":{
      "scriptId":"u59"},
    "d5b81ece76344e978499482aad657320":{
      "scriptId":"u60"},
    "8c8b598838f840fdb27e536250504a74":{
      "scriptId":"u61"},
    "2bcbb5c1542b4622b918805dcced7c18":{
      "scriptId":"u62"},
    "56fb6e0703c547dab305edd8e80cf43d":{
      "scriptId":"u63"},
    "2ec0e3189d8f4ed0ab4c779e3310f5f0":{
      "scriptId":"u64"},
    "d143d29690804761a9e07c75e61838ef":{
      "scriptId":"u65"},
    "6404148a1eac49389f155105faa05fb4":{
      "scriptId":"u66"},
    "738715c91ec042f4ac990eab9c2ec028":{
      "scriptId":"u67"},
    "ebfd5976cc684b59927182b9b13ab964":{
      "scriptId":"u68"},
    "c0bd81c4332a4d02b18a0e0238c438c0":{
      "scriptId":"u69"},
    "c51bdf58157e456fade324f4ace8d5da":{
      "scriptId":"u70"},
    "c3c4de28cc5f42c8bd027e54fff2d0d7":{
      "scriptId":"u71"},
    "0a87b6b42ad74af094024ad0ec9ae9f9":{
      "scriptId":"u72"},
    "7db403111d1f4d5092f51b91758313c8":{
      "scriptId":"u73"},
    "e2cd753e21ad4b47b6030a0b24bfa0f2":{
      "scriptId":"u74"},
    "4dc040c10cd042098b46c2e91c99e542":{
      "scriptId":"u75"},
    "94288fa6f6b34896b28e5a10bce0543e":{
      "scriptId":"u76"},
    "38330ef6df6d47c782a62dbf2d4f7bd7":{
      "scriptId":"u77"},
    "695176f5e3cd48559f6dccf8bc879a51":{
      "scriptId":"u78"},
    "39f3d5f77c1a4c68a61f052925d228f9":{
      "scriptId":"u79"},
    "886104b76c4d4eb8bd9569a256f591ce":{
      "scriptId":"u80"},
    "eee9ea7fa05c4b77bd4f22c30071f39c":{
      "scriptId":"u81"},
    "02b686f023aa417b95c7ceb4273f4e61":{
      "scriptId":"u82"}}});