$axure.loadCurrentPage({
  "url":"区域查询.html",
  "generationDate":new Date(1383038968398.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/系统登录默认页/bg.jpg",
    "width":1000,
    "height":750},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"e65a0f9279a04b288d10db1bde58397c",
    "type":"Axure:Page",
    "name":"区域查询",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3fb658a83ec148b4bab64d57fcabe6b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":160},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"705b10b366fe4296af0fe5d6523f6f71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":160},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4fed4824be514be3a622224dd31b70f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":338,
              "y":160},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe07d6ba4947488c8067c5f949ad4795",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":338,
                  "y":160},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de8cb3339e0444b9a046246e92cbd576",
          "label":"菜单",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":170},
            "size":{
              "width":141,
              "height":520}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"3809df9a55ce4c499f283e9c7c93f907",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"62df5b1a03e1401980c3d185e9613884",
                  "label":"",
                  "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":10}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"79a8b0a82fa745d197d5b96186fb4d45",
                  "label":"",
                  "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":18},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c466eb719cc749af8a01893f556be8ab",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":18},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ea437c69517b4a479bc498de08dc4250",
                  "label":"",
                  "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":43}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"b087be34bc7740fc944af866cee2afb6",
                  "label":"",
                  "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":51},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"145ea6c816f646eab41fb94d57ea21e1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":51},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 注册新会员",
                              "target":{
                                "targetType":"page",
                                "url":"注册新会员.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ef4799e0b378486ea8f99065084fed09",
                  "label":"",
                  "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":76},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"6b347e85e3ec4f5986f15169d4471f5f",
                  "label":"",
                  "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":84},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ff19735c298f40c4b693ccc0be734652",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":84},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 提现明细",
                              "target":{
                                "targetType":"page",
                                "url":"提现明细.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b21958d9d5224389bd91f9cd568b8fdc",
                  "label":"",
                  "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":109},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"dca93708a8fa4862966a91a95b2e2153",
                  "label":"",
                  "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":117},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ce54ba57b4d54b889e4911773a0fc778",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":117},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 报单购物",
                              "target":{
                                "targetType":"page",
                                "url":"报单购物.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9a2c95807b044640b08569aed1103ac8",
                  "label":"",
                  "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":142},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"9298c42b35e94c1ba0aa4e6571d5853e",
                  "label":"",
                  "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":150},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5196253e15b44bb390b8804cef3892a7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":150},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 奖励查询",
                              "target":{
                                "targetType":"page",
                                "url":"奖励查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b106b99bc63f41b0b7fc80c9a2669fbf",
                  "label":"",
                  "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":279},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"1b496d14e6704ceabcd53067f50bc766",
                  "label":"",
                  "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":287},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"027d2dda38f04eb79be8c3ec0be52367",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":287},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c03f398763bc48c0a742d2d1b07c66b8",
                  "label":"",
                  "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":31,
                      "y":184},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7bcfffc3a8d34460ac6f1a5b5e8b520b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":31,
                          "y":184},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 奖励查询",
                              "target":{
                                "targetType":"page",
                                "url":"奖励查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7dfa7395964d4c1b8f1bdfb26a3300f8",
                  "label":"",
                  "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":208},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"63e03edcfebd4968bb33eda73e36d0a6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":208},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 推荐查询",
                              "target":{
                                "targetType":"page",
                                "url":"推荐查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9479654511a540e7b471484cedebb0f6",
                  "label":"",
                  "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":231},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2b813795fde14876afebe9718ab0a336",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":231},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 区域查询",
                              "target":{
                                "targetType":"page",
                                "url":"区域查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a3bd9b64f1774ee6b792298767f101c3",
                  "label":"",
                  "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":253},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"562e810bbb674e02997f4948b5234607",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"de8cb3339e0444b9a046246e92cbd576",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":253},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 操作须知",
                              "target":{
                                "targetType":"page",
                                "url":"操作须知.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"4e6223d628af454db36d2c91f46192f7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":571,
              "y":250},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3a7caa9b7d24c24965a2b589650e378",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":571,
                  "y":250},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/安排区域/u6.gif"}},
{
          "id":"ede6c08db620434fbc97267f44e47c92",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":272,
              "y":204},
            "size":{
              "width":446,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea7e5fed02b24ad0a23e9594a1da50d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":272,
                  "y":204},
                "size":{
                  "width":446,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7a1b73a54b544ea9aaa142e9cab4b13",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":250,
              "y":200},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abc1dcab052745e5b38076f390cc5804",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":250,
                  "y":200},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认激活/u144.png"}},
{
          "id":"ed0a5e38f31a47ff8b393072a46896bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":547,
              "y":300},
            "size":{
              "width":88,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fc389d59d5242f489771dff762af295",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":547,
                  "y":300},
                "size":{
                  "width":88,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4397c046dfd4580ac3b998aad457e98",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":443,
              "y":324},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5018463d8b2c47e3809f5dcff6b15cf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":443,
                  "y":324},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/安排区域/u6.gif"}},
{
          "id":"f0d4f88434554390b0c20632f8bae90c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":419,
              "y":374},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27f29e6121dd46e2935bc72b8773ceb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":419,
                  "y":374},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5ff585a6cdb248f68709b5817b017a35",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":719,
              "y":324},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c206bb9789a2421fb15c0398e0cfb63e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":719,
                  "y":324},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/安排区域/u6.gif"}},
{
          "id":"0b29c92717e1493b80e0fdde2c206eb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":695,
              "y":374},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce6c8c1feeda47ab9d86f0c3bca64f1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":695,
                  "y":374},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d87d8a58c16e46c18c347829b3f0eb74",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":351,
              "y":414},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ec7b95dd54a46628379d23d1fc1a5c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":351,
                  "y":414},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/安排区域/u6.gif"}},
{
          "id":"9d51d33b00d44274a81109f281013c2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":327,
              "y":464},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70d72729c30a4e99bda641025da6a460",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":327,
                  "y":464},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dac6766248e1430c98d08d48fbe32eea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":659,
              "y":414},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8084e8aab4cd4fb7aaa3631d3845113b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":659,
                  "y":414},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/安排区域/u6.gif"}},
{
          "id":"644bd512ed1345828abde5ef00d47072",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":635,
              "y":464},
            "size":{
              "width":116,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a65e1db793548ad9496a5b517054ae9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":635,
                  "y":464},
                "size":{
                  "width":116,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6b350709f414cb2977f5fb468075894",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":792,
              "y":414},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6733ec0fc66b4215afccc243b313cb56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":792,
                  "y":414},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/安排区域/u6.gif"}},
{
          "id":"597feae634384b2ebf9e0469c658998f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":768,
              "y":464},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d7eb7335e464363a1cc06db62b73b27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":768,
                  "y":464},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d41a00c8ac24b78bc34743b1d96edfc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":510},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47e96f94607c4227b4067480e96affbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":510},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/安排区域/u6.gif"}},
{
          "id":"2be61f624e1841ad9b2c17cf1b38246a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":560},
            "size":{
              "width":116,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b08554761408469f996b90b8349a83e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":560},
                "size":{
                  "width":116,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2da3d42f65a4f8f937714808cfe268c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":396,
              "y":510},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa0b5d27b20b43cdb08dfcca11902844",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":396,
                  "y":510},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/安排区域/u6.gif"}},
{
          "id":"3a519210edb24482835441108ada258e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":372,
              "y":560},
            "size":{
              "width":116,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22eebee386b94682b1f1457f08fd0921",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":372,
                  "y":560},
                "size":{
                  "width":116,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfde259dcc744cb3b569b4b1cc557533",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":631,
              "y":510},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05bf23fbd499491ca1186852aa2ffded",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":631,
                  "y":510},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/安排区域/u6.gif"}},
{
          "id":"df6d2159b194485b86975383e301cf6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":607,
              "y":560},
            "size":{
              "width":116,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d88c29ae7654ae7b93c837dc443a77d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":607,
                  "y":560},
                "size":{
                  "width":116,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d43bc0fa51048c59f4951f0de6e739b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":414},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49b647a2048f40a5b12faac1fe88fb0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":504,
                  "y":414},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/安排区域/u6.gif"}},
{
          "id":"f9fde27d2bd445e885e7c3410c1d3bc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":464},
            "size":{
              "width":109,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70014d3213bb4e17a278be82d2f41b60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":464},
                "size":{
                  "width":109,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3fb0a24534024ab09ae01efbce88ef08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":506,
              "y":530},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34520143ccc042bf906cd6a10deb32bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":506,
                  "y":530},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2dd62b316594dedb9e433b840b3c18f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":724,
              "y":534},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"944847a80aad4894b59248e453094afe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":724,
                  "y":534},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2619ca054b3244c7a5e90a01558af863",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":809,
              "y":534},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaff3136bcda483ca3d6f87846d57a8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":809,
                  "y":534},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06d696eaf21344779c127395900a7718",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":911,
              "y":534},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4136661e98d3468a84502f91880813e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":911,
                  "y":534},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e6243b60aae416ca533ee5180bf231e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":80},
            "size":{
              "width":162,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a75d1acb26b348bdad788d7560c1c5db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":80},
                "size":{
                  "width":162,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c60e4eb33d3d4a098614ac970f4408bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":306,
              "y":15},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a4089f72c224a87b4ec6c1a495592f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":15},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f64f00d1e7274ab78b8296e9213e2192",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":408,
              "y":15},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f4fcf2d812841d9bdfa40805353183a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":408,
                  "y":15},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22a11f816ed14fa1a103c9feeb0b2a18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":785,
              "y":15},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da9f832f8c944758bac814db6b73eed7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":785,
                  "y":15},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改本人密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改本人密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"754026ee220b4747843845cf73e066e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":868,
              "y":15},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d00286f5a84a44a9b3e42ec299e44689",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":868,
                  "y":15},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97dc41329b6b4bed99a78219f1708ee3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":617,
              "y":15},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03a16d4bf662435d873dec9b80d23dba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":617,
                  "y":15},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72000266a2794524b242d992906ae276",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":15},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d62ae1cab924cc9a8125e129dc9fe5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":708,
                  "y":15},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb50bdaadbf34d44904039d09bfdc3aa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":737,
              "y":15},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4bfb1dd2d8b4f93b896fdf9473e87ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":737,
                  "y":15},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u121.png"}},
{
          "id":"e028947b1461494d8eaeba8355ce65fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":15},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fa084c04db647bf9fc3b8356d15cc22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":15},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"715fb223a431465b9d299f80780898b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":671,
              "y":15},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fdd27e947d64647a086eb880367897d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":671,
                  "y":15},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c0fb8db987a4860ba41598af4b897fe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":526,
              "y":14},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4584df917bb4db7921b858a713b535d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":526,
                  "y":14},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 购物车",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u127.png"}},
{
          "id":"83103e8dbdf643ffa9db135f0a24a9b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":3},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59fa8a109177480495d5d35d961037fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":542,
                  "y":3},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/系统登录默认页/u129.png"}},
{
          "id":"882787e7f52548378249a7b368c3301e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":547,
              "y":1},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a827e613fcc420c8034edf3ac9d1d99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":547,
                  "y":1},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "d2415d04c3894ee2a19022d44e11f35b":{
      "packageId":"d2415d04c3894ee2a19022d44e11f35b",
      "type":"Axure:Master",
      "name":"nav",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7837bfaf60f741f3a6519b77012fd40a",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"7a89eecc0e584f76adbdcdcf2a6c58e7"}]}},
    "7a89eecc0e584f76adbdcdcf2a6c58e7":{
      "packageId":"7a89eecc0e584f76adbdcdcf2a6c58e7",
      "type":"Axure:Master",
      "name":"nav1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"82d5041198434b178bff196e00dfbfe6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":141,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7824ebb366034aba98ee9785a7394f11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":141,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg"}}]}}},
  "objectPaths":{
    "3fb658a83ec148b4bab64d57fcabe6b6":{
      "scriptId":"u0"},
    "705b10b366fe4296af0fe5d6523f6f71":{
      "scriptId":"u1"},
    "4fed4824be514be3a622224dd31b70f5":{
      "scriptId":"u2"},
    "fe07d6ba4947488c8067c5f949ad4795":{
      "scriptId":"u3"},
    "de8cb3339e0444b9a046246e92cbd576":{
      "scriptId":"u4"},
    "62df5b1a03e1401980c3d185e9613884":{
      "scriptId":"u5",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u6",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u7"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u8"}}},
    "79a8b0a82fa745d197d5b96186fb4d45":{
      "scriptId":"u9"},
    "c466eb719cc749af8a01893f556be8ab":{
      "scriptId":"u10"},
    "ea437c69517b4a479bc498de08dc4250":{
      "scriptId":"u11",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u12",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u13"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u14"}}},
    "b087be34bc7740fc944af866cee2afb6":{
      "scriptId":"u15"},
    "145ea6c816f646eab41fb94d57ea21e1":{
      "scriptId":"u16"},
    "ef4799e0b378486ea8f99065084fed09":{
      "scriptId":"u17",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u18",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u19"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u20"}}},
    "6b347e85e3ec4f5986f15169d4471f5f":{
      "scriptId":"u21"},
    "ff19735c298f40c4b693ccc0be734652":{
      "scriptId":"u22"},
    "b21958d9d5224389bd91f9cd568b8fdc":{
      "scriptId":"u23",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u24",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u25"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u26"}}},
    "dca93708a8fa4862966a91a95b2e2153":{
      "scriptId":"u27"},
    "ce54ba57b4d54b889e4911773a0fc778":{
      "scriptId":"u28"},
    "9a2c95807b044640b08569aed1103ac8":{
      "scriptId":"u29",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u30",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u31"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u32"}}},
    "9298c42b35e94c1ba0aa4e6571d5853e":{
      "scriptId":"u33"},
    "5196253e15b44bb390b8804cef3892a7":{
      "scriptId":"u34"},
    "b106b99bc63f41b0b7fc80c9a2669fbf":{
      "scriptId":"u35",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u36",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u37"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u38"}}},
    "1b496d14e6704ceabcd53067f50bc766":{
      "scriptId":"u39"},
    "027d2dda38f04eb79be8c3ec0be52367":{
      "scriptId":"u40"},
    "c03f398763bc48c0a742d2d1b07c66b8":{
      "scriptId":"u41"},
    "7bcfffc3a8d34460ac6f1a5b5e8b520b":{
      "scriptId":"u42"},
    "7dfa7395964d4c1b8f1bdfb26a3300f8":{
      "scriptId":"u43"},
    "63e03edcfebd4968bb33eda73e36d0a6":{
      "scriptId":"u44"},
    "9479654511a540e7b471484cedebb0f6":{
      "scriptId":"u45"},
    "2b813795fde14876afebe9718ab0a336":{
      "scriptId":"u46"},
    "a3bd9b64f1774ee6b792298767f101c3":{
      "scriptId":"u47"},
    "562e810bbb674e02997f4948b5234607":{
      "scriptId":"u48"},
    "4e6223d628af454db36d2c91f46192f7":{
      "scriptId":"u49"},
    "b3a7caa9b7d24c24965a2b589650e378":{
      "scriptId":"u50"},
    "ede6c08db620434fbc97267f44e47c92":{
      "scriptId":"u51"},
    "ea7e5fed02b24ad0a23e9594a1da50d5":{
      "scriptId":"u52"},
    "b7a1b73a54b544ea9aaa142e9cab4b13":{
      "scriptId":"u53"},
    "abc1dcab052745e5b38076f390cc5804":{
      "scriptId":"u54"},
    "ed0a5e38f31a47ff8b393072a46896bf":{
      "scriptId":"u55"},
    "7fc389d59d5242f489771dff762af295":{
      "scriptId":"u56"},
    "c4397c046dfd4580ac3b998aad457e98":{
      "scriptId":"u57"},
    "5018463d8b2c47e3809f5dcff6b15cf1":{
      "scriptId":"u58"},
    "f0d4f88434554390b0c20632f8bae90c":{
      "scriptId":"u59"},
    "27f29e6121dd46e2935bc72b8773ceb0":{
      "scriptId":"u60"},
    "5ff585a6cdb248f68709b5817b017a35":{
      "scriptId":"u61"},
    "c206bb9789a2421fb15c0398e0cfb63e":{
      "scriptId":"u62"},
    "0b29c92717e1493b80e0fdde2c206eb7":{
      "scriptId":"u63"},
    "ce6c8c1feeda47ab9d86f0c3bca64f1e":{
      "scriptId":"u64"},
    "d87d8a58c16e46c18c347829b3f0eb74":{
      "scriptId":"u65"},
    "0ec7b95dd54a46628379d23d1fc1a5c6":{
      "scriptId":"u66"},
    "9d51d33b00d44274a81109f281013c2a":{
      "scriptId":"u67"},
    "70d72729c30a4e99bda641025da6a460":{
      "scriptId":"u68"},
    "dac6766248e1430c98d08d48fbe32eea":{
      "scriptId":"u69"},
    "8084e8aab4cd4fb7aaa3631d3845113b":{
      "scriptId":"u70"},
    "644bd512ed1345828abde5ef00d47072":{
      "scriptId":"u71"},
    "1a65e1db793548ad9496a5b517054ae9":{
      "scriptId":"u72"},
    "e6b350709f414cb2977f5fb468075894":{
      "scriptId":"u73"},
    "6733ec0fc66b4215afccc243b313cb56":{
      "scriptId":"u74"},
    "597feae634384b2ebf9e0469c658998f":{
      "scriptId":"u75"},
    "5d7eb7335e464363a1cc06db62b73b27":{
      "scriptId":"u76"},
    "2d41a00c8ac24b78bc34743b1d96edfc":{
      "scriptId":"u77"},
    "47e96f94607c4227b4067480e96affbd":{
      "scriptId":"u78"},
    "2be61f624e1841ad9b2c17cf1b38246a":{
      "scriptId":"u79"},
    "b08554761408469f996b90b8349a83e1":{
      "scriptId":"u80"},
    "d2da3d42f65a4f8f937714808cfe268c":{
      "scriptId":"u81"},
    "aa0b5d27b20b43cdb08dfcca11902844":{
      "scriptId":"u82"},
    "3a519210edb24482835441108ada258e":{
      "scriptId":"u83"},
    "22eebee386b94682b1f1457f08fd0921":{
      "scriptId":"u84"},
    "cfde259dcc744cb3b569b4b1cc557533":{
      "scriptId":"u85"},
    "05bf23fbd499491ca1186852aa2ffded":{
      "scriptId":"u86"},
    "df6d2159b194485b86975383e301cf6e":{
      "scriptId":"u87"},
    "8d88c29ae7654ae7b93c837dc443a77d":{
      "scriptId":"u88"},
    "6d43bc0fa51048c59f4951f0de6e739b":{
      "scriptId":"u89"},
    "49b647a2048f40a5b12faac1fe88fb0d":{
      "scriptId":"u90"},
    "f9fde27d2bd445e885e7c3410c1d3bc9":{
      "scriptId":"u91"},
    "70014d3213bb4e17a278be82d2f41b60":{
      "scriptId":"u92"},
    "3fb0a24534024ab09ae01efbce88ef08":{
      "scriptId":"u93"},
    "34520143ccc042bf906cd6a10deb32bf":{
      "scriptId":"u94"},
    "a2dd62b316594dedb9e433b840b3c18f":{
      "scriptId":"u95"},
    "944847a80aad4894b59248e453094afe":{
      "scriptId":"u96"},
    "2619ca054b3244c7a5e90a01558af863":{
      "scriptId":"u97"},
    "eaff3136bcda483ca3d6f87846d57a8e":{
      "scriptId":"u98"},
    "06d696eaf21344779c127395900a7718":{
      "scriptId":"u99"},
    "4136661e98d3468a84502f91880813e8":{
      "scriptId":"u100"},
    "3e6243b60aae416ca533ee5180bf231e":{
      "scriptId":"u101"},
    "a75d1acb26b348bdad788d7560c1c5db":{
      "scriptId":"u102"},
    "c60e4eb33d3d4a098614ac970f4408bc":{
      "scriptId":"u103"},
    "5a4089f72c224a87b4ec6c1a495592f6":{
      "scriptId":"u104"},
    "f64f00d1e7274ab78b8296e9213e2192":{
      "scriptId":"u105"},
    "2f4fcf2d812841d9bdfa40805353183a":{
      "scriptId":"u106"},
    "22a11f816ed14fa1a103c9feeb0b2a18":{
      "scriptId":"u107"},
    "da9f832f8c944758bac814db6b73eed7":{
      "scriptId":"u108"},
    "754026ee220b4747843845cf73e066e8":{
      "scriptId":"u109"},
    "d00286f5a84a44a9b3e42ec299e44689":{
      "scriptId":"u110"},
    "97dc41329b6b4bed99a78219f1708ee3":{
      "scriptId":"u111"},
    "03a16d4bf662435d873dec9b80d23dba":{
      "scriptId":"u112"},
    "72000266a2794524b242d992906ae276":{
      "scriptId":"u113"},
    "3d62ae1cab924cc9a8125e129dc9fe5d":{
      "scriptId":"u114"},
    "eb50bdaadbf34d44904039d09bfdc3aa":{
      "scriptId":"u115"},
    "b4bfb1dd2d8b4f93b896fdf9473e87ec":{
      "scriptId":"u116"},
    "e028947b1461494d8eaeba8355ce65fd":{
      "scriptId":"u117"},
    "5fa084c04db647bf9fc3b8356d15cc22":{
      "scriptId":"u118"},
    "715fb223a431465b9d299f80780898b4":{
      "scriptId":"u119"},
    "9fdd27e947d64647a086eb880367897d":{
      "scriptId":"u120"},
    "9c0fb8db987a4860ba41598af4b897fe":{
      "scriptId":"u121"},
    "f4584df917bb4db7921b858a713b535d":{
      "scriptId":"u122"},
    "83103e8dbdf643ffa9db135f0a24a9b7":{
      "scriptId":"u123"},
    "59fa8a109177480495d5d35d961037fa":{
      "scriptId":"u124"},
    "882787e7f52548378249a7b368c3301e":{
      "scriptId":"u125"},
    "4a827e613fcc420c8034edf3ac9d1d99":{
      "scriptId":"u126"}}});