$axure.loadCurrentPage({
  "url":"报单购物.html",
  "generationDate":new Date(1383038962584.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/系统登录默认页/bg.jpg",
    "width":1000,
    "height":750},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"0aa658b9201640da926defa83d228d7e",
    "type":"Axure:Page",
    "name":"报单购物",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7d454231933447ba94a822dacd451bc4",
          "label":"菜单",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":170},
            "size":{
              "width":141,
              "height":520}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"28ba1b5d6a9f481dbe967d45bed9707d",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a06cae58a1124c8990693dad1fd3029c",
                  "label":"",
                  "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":10}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"9f7bff200cec4284b5bbb8b678114c94",
                  "label":"",
                  "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":18},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"792c697be11440be9cf76e5a9a086c1e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":18},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"849aad6bfcbd46f39c0ca0febd5c112f",
                  "label":"",
                  "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":43}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"7d0a3a47044249498e3c3503fbac0a76",
                  "label":"",
                  "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":51},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"42fcffc583a74323bd7d74ef1f58d56a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":51},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 注册新会员",
                              "target":{
                                "targetType":"page",
                                "url":"注册新会员.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"db61223c8abd43e1a2febdab870f6591",
                  "label":"",
                  "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":76},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"edfd866877eb4964b48f4f848cf47043",
                  "label":"",
                  "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":84},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3f2ab3f572054e2cab5f59628c078cbb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":84},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 提现明细",
                              "target":{
                                "targetType":"page",
                                "url":"提现明细.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7d8f3430624b475ea6dd938785a2d9d0",
                  "label":"",
                  "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":109},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"1879796e21bc4fc6963b491b489b449b",
                  "label":"",
                  "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":117},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e8c5d40499f846feb7eb5b64b131866d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":117},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 报单购物",
                              "target":{
                                "targetType":"page",
                                "url":"报单购物.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d433f4246fe94cf5a7fac2b374e9f466",
                  "label":"",
                  "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":272},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"4b5bfc7021654a739942e48de93110fd",
                  "label":"",
                  "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":280},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f38895c7dd5047fd804cfe022e2f5ed2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":280},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 奖励查询",
                              "target":{
                                "targetType":"page",
                                "url":"奖励查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"66e51a6287d9481ea36b2247b09680b2",
                  "label":"",
                  "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":305},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"cbf2fbdb7bff4a049dc9e18e17c93c62",
                  "label":"",
                  "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":313},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8f74459c52df4e36ac76a80f9f5a9734",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":313},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8e1ee95af1ae4a0c859196b214015a19",
                  "label":"",
                  "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00,
                      "opacity":1},
                    "location":{
                      "x":31,
                      "y":149},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bd939f3acfa145c1b3e8dbf40e63ba08",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00,
                          "opacity":1},
                        "location":{
                          "x":31,
                          "y":149},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 报单购物",
                              "target":{
                                "targetType":"page",
                                "url":"报单购物.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"884988a2a54a4fb9ab624cc6959d675a",
                  "label":"",
                  "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":173},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7de8ad721ebe4266bd0d261fa0800069",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":173},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 确认激活",
                              "target":{
                                "targetType":"page",
                                "url":"确认激活.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f357e6299cf5411191a0fa9e97d24457",
                  "label":"",
                  "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":196},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd3e89ba92c549b095e402ee3d8e71bb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":196},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 重消购货",
                              "target":{
                                "targetType":"page",
                                "url":"重消购货.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2163eaefbacf456c80ef77e2571c7164",
                  "label":"",
                  "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":218},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b8f0af6805534b22b979a5723e12562d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":218},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 辅消购货",
                              "target":{
                                "targetType":"page",
                                "url":"辅消购货.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d3a142e89c7043499de56ac6a9a113be",
                  "label":"",
                  "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":242},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"845c9e6e7b8944edb104a515fbb399c7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d454231933447ba94a822dacd451bc4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":242},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 购货管理",
                              "target":{
                                "targetType":"page",
                                "url":"购货管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"c4bd09f72ab3480db82ecd8f741221a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":160},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8749d9e13ec43c09dbb65db208f112b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":160},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2591603adb0447c0aebcce0953a886d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":338,
              "y":160},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0bac6ca883b419e8fe4c60fa6da4768",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":338,
                  "y":160},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b887066c87b64f70ab3f96e969d8d3f2",
          "label":"main",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":196},
            "size":{
              "width":650,
              "height":504}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"53b18155d2ee4ec7997d85a600b23683",
              "label":"a",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d0d426b2e85c4f54a5645ec9e2c3bfd2",
                  "label":"",
                  "parentDynamicPanel":"b887066c87b64f70ab3f96e969d8d3f2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":10,
                      "y":28},
                    "size":{
                      "width":640,
                      "height":212}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"baa7bbfbf0cb4ac49a4d6e85b6fcd40b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b887066c87b64f70ab3f96e969d8d3f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":10,
                          "y":28},
                        "size":{
                          "width":640,
                          "height":212}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f294d56112174dedbdccaf1de28349f6",
                  "label":"",
                  "parentDynamicPanel":"b887066c87b64f70ab3f96e969d8d3f2",
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fontName":"'华文行楷 Oblique', '华文行楷'",
                    "fontSize":"16px",
                    "fontStyle":"oblique",
                    "location":{
                      "x":520,
                      "y":250},
                    "size":{
                      "width":100,
                      "height":26},
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5f29370dd1094cb985f03f0e7ad1325f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b887066c87b64f70ab3f96e969d8d3f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'华文行楷 Oblique', '华文行楷'",
                        "fontSize":"16px",
                        "fontStyle":"oblique",
                        "location":{
                          "x":520,
                          "y":250},
                        "size":{
                          "width":100,
                          "height":26},
                        "outerShadow":{
                          "on":true,
                          "offsetX":5,
                          "offsetY":5,
                          "blurRadius":5,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.349019607843137}}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 main 到 b",
                              "panelsToStates":[{
                                  "panelPath":["b887066c87b64f70ab3f96e969d8d3f2"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/申请提现/u106.png"}},
{
                  "id":"0663e82b857e4283ad6a38dffde2c150",
                  "label":"",
                  "parentDynamicPanel":"b887066c87b64f70ab3f96e969d8d3f2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":32,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1e1d4ed23d9448419174219f178203a4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b887066c87b64f70ab3f96e969d8d3f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":10,
                          "y":10},
                        "size":{
                          "width":32,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/权限管理/u64.png"}}]},
{
              "id":"05bcb2efc5f04a16900d2869a461db70",
              "label":"b",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c0ea72477ddf45439994de1314d2978c",
                  "label":"",
                  "parentDynamicPanel":"b887066c87b64f70ab3f96e969d8d3f2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":62,
                      "y":80},
                    "size":{
                      "width":131,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2338683759114c48814a0dd0fc1d9ac7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b887066c87b64f70ab3f96e969d8d3f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":62,
                          "y":80},
                        "size":{
                          "width":131,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b4ca80fd449b4470acdfc9cdfd935f95",
                  "label":"",
                  "parentDynamicPanel":"b887066c87b64f70ab3f96e969d8d3f2",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":75.5},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"3caa35399d034728ae29ed7391194e42",
                  "label":"",
                  "parentDynamicPanel":"b887066c87b64f70ab3f96e969d8d3f2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xA5006600},
                        "linePattern":"solid"}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFDFEACA},
                    "location":{
                      "x":350,
                      "y":136},
                    "size":{
                      "width":70,
                      "height":24},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF6DB847},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c979cd04f9ba42cbad2fa9a852affa86",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b887066c87b64f70ab3f96e969d8d3f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xA5006600},
                            "linePattern":"solid"}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDFEACA},
                        "location":{
                          "x":350,
                          "y":136},
                        "size":{
                          "width":70,
                          "height":24},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF6DB847},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 报单购物表单",
                              "target":{
                                "targetType":"page",
                                "url":"报单购物表单.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/公告详细页面/u57.png",
                    "mouseOver~":"images/公告详细页面/u57_mouseOver.png"}}]}]},
{
          "id":"e617983760ef4942b525226c4f37e8bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":74},
            "size":{
              "width":172,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23d78c53b8414d4b8958f4422f5af286",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":74},
                "size":{
                  "width":172,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60d8cd80cf5e4a92b1759c68574552c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":306,
              "y":15},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d7a3a733e714c9f9a115d9196f88bc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":15},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9122cf05c636488c9c77ef3922990e60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":408,
              "y":15},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d45a6ccf32340f180909ba0f608a7e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":408,
                  "y":15},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"107c6c4127d64892a0e04836fc2ca66b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":785,
              "y":15},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccac05f96de6407da418921eb72616c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":785,
                  "y":15},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改本人密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改本人密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f31e20f916204f89a06aee179a39b324",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":868,
              "y":15},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95308dd18162470da26e6ae62ffcb7f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":868,
                  "y":15},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b4abde060be4274826a914ea0d7e8a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":617,
              "y":15},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a32ff2d3335744c7a6cd00a4b5cb9ce9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":617,
                  "y":15},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6bd277986334c758bcf9ddaaad44ec3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":15},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bc32781987c43edb97d90a335951fcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":708,
                  "y":15},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a7b330660b24847ab0fb979fcba053e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":737,
              "y":15},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65da3f6807d14d248894ba40d1f0914b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":737,
                  "y":15},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u121.png"}},
{
          "id":"26f7ebde365845319a9786a86d7d4578",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":15},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cf3d68afa2a4414ba30d569f8333ec0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":15},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ee456fee3be4ef69b6946ce1f9c5854",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":671,
              "y":15},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c280404aa4be4d79bf63fd083086d74b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":671,
                  "y":15},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e711b83d756c45648534668d377b67fd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":526,
              "y":14},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c927780370a0440284ddf7ad44e65e8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":526,
                  "y":14},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 购物车",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u127.png"}},
{
          "id":"80ae1977c0be4a7abbfc1ba7d06482f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":3},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97aba5c15a6b46f09765b1fba3c1fc5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":542,
                  "y":3},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/系统登录默认页/u129.png"}},
{
          "id":"ecd00336f0b64a06b19e966442ba9451",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":547,
              "y":1},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47c71daf29f44431a3141cfc5666714c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":547,
                  "y":1},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "d2415d04c3894ee2a19022d44e11f35b":{
      "packageId":"d2415d04c3894ee2a19022d44e11f35b",
      "type":"Axure:Master",
      "name":"nav",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7837bfaf60f741f3a6519b77012fd40a",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"7a89eecc0e584f76adbdcdcf2a6c58e7"}]}},
    "7a89eecc0e584f76adbdcdcf2a6c58e7":{
      "packageId":"7a89eecc0e584f76adbdcdcf2a6c58e7",
      "type":"Axure:Master",
      "name":"nav1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"82d5041198434b178bff196e00dfbfe6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":141,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7824ebb366034aba98ee9785a7394f11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":141,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg"}}]}}},
  "objectPaths":{
    "7d454231933447ba94a822dacd451bc4":{
      "scriptId":"u0"},
    "a06cae58a1124c8990693dad1fd3029c":{
      "scriptId":"u1",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u2",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u3"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u4"}}},
    "9f7bff200cec4284b5bbb8b678114c94":{
      "scriptId":"u5"},
    "792c697be11440be9cf76e5a9a086c1e":{
      "scriptId":"u6"},
    "849aad6bfcbd46f39c0ca0febd5c112f":{
      "scriptId":"u7",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u8",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u9"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u10"}}},
    "7d0a3a47044249498e3c3503fbac0a76":{
      "scriptId":"u11"},
    "42fcffc583a74323bd7d74ef1f58d56a":{
      "scriptId":"u12"},
    "db61223c8abd43e1a2febdab870f6591":{
      "scriptId":"u13",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u14",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u15"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u16"}}},
    "edfd866877eb4964b48f4f848cf47043":{
      "scriptId":"u17"},
    "3f2ab3f572054e2cab5f59628c078cbb":{
      "scriptId":"u18"},
    "7d8f3430624b475ea6dd938785a2d9d0":{
      "scriptId":"u19",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u20",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u21"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u22"}}},
    "1879796e21bc4fc6963b491b489b449b":{
      "scriptId":"u23"},
    "e8c5d40499f846feb7eb5b64b131866d":{
      "scriptId":"u24"},
    "d433f4246fe94cf5a7fac2b374e9f466":{
      "scriptId":"u25",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u26",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u27"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u28"}}},
    "4b5bfc7021654a739942e48de93110fd":{
      "scriptId":"u29"},
    "f38895c7dd5047fd804cfe022e2f5ed2":{
      "scriptId":"u30"},
    "66e51a6287d9481ea36b2247b09680b2":{
      "scriptId":"u31",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u32",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u33"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u34"}}},
    "cbf2fbdb7bff4a049dc9e18e17c93c62":{
      "scriptId":"u35"},
    "8f74459c52df4e36ac76a80f9f5a9734":{
      "scriptId":"u36"},
    "8e1ee95af1ae4a0c859196b214015a19":{
      "scriptId":"u37"},
    "bd939f3acfa145c1b3e8dbf40e63ba08":{
      "scriptId":"u38"},
    "884988a2a54a4fb9ab624cc6959d675a":{
      "scriptId":"u39"},
    "7de8ad721ebe4266bd0d261fa0800069":{
      "scriptId":"u40"},
    "f357e6299cf5411191a0fa9e97d24457":{
      "scriptId":"u41"},
    "cd3e89ba92c549b095e402ee3d8e71bb":{
      "scriptId":"u42"},
    "2163eaefbacf456c80ef77e2571c7164":{
      "scriptId":"u43"},
    "b8f0af6805534b22b979a5723e12562d":{
      "scriptId":"u44"},
    "d3a142e89c7043499de56ac6a9a113be":{
      "scriptId":"u45"},
    "845c9e6e7b8944edb104a515fbb399c7":{
      "scriptId":"u46"},
    "c4bd09f72ab3480db82ecd8f741221a0":{
      "scriptId":"u47"},
    "c8749d9e13ec43c09dbb65db208f112b":{
      "scriptId":"u48"},
    "2591603adb0447c0aebcce0953a886d1":{
      "scriptId":"u49"},
    "c0bac6ca883b419e8fe4c60fa6da4768":{
      "scriptId":"u50"},
    "b887066c87b64f70ab3f96e969d8d3f2":{
      "scriptId":"u51"},
    "d0d426b2e85c4f54a5645ec9e2c3bfd2":{
      "scriptId":"u52"},
    "baa7bbfbf0cb4ac49a4d6e85b6fcd40b":{
      "scriptId":"u53"},
    "f294d56112174dedbdccaf1de28349f6":{
      "scriptId":"u54"},
    "5f29370dd1094cb985f03f0e7ad1325f":{
      "scriptId":"u55"},
    "0663e82b857e4283ad6a38dffde2c150":{
      "scriptId":"u56"},
    "1e1d4ed23d9448419174219f178203a4":{
      "scriptId":"u57"},
    "c0ea72477ddf45439994de1314d2978c":{
      "scriptId":"u58"},
    "2338683759114c48814a0dd0fc1d9ac7":{
      "scriptId":"u59"},
    "b4ca80fd449b4470acdfc9cdfd935f95":{
      "scriptId":"u60"},
    "3caa35399d034728ae29ed7391194e42":{
      "scriptId":"u61"},
    "c979cd04f9ba42cbad2fa9a852affa86":{
      "scriptId":"u62"},
    "e617983760ef4942b525226c4f37e8bb":{
      "scriptId":"u63"},
    "23d78c53b8414d4b8958f4422f5af286":{
      "scriptId":"u64"},
    "60d8cd80cf5e4a92b1759c68574552c3":{
      "scriptId":"u65"},
    "0d7a3a733e714c9f9a115d9196f88bc4":{
      "scriptId":"u66"},
    "9122cf05c636488c9c77ef3922990e60":{
      "scriptId":"u67"},
    "2d45a6ccf32340f180909ba0f608a7e1":{
      "scriptId":"u68"},
    "107c6c4127d64892a0e04836fc2ca66b":{
      "scriptId":"u69"},
    "ccac05f96de6407da418921eb72616c8":{
      "scriptId":"u70"},
    "f31e20f916204f89a06aee179a39b324":{
      "scriptId":"u71"},
    "95308dd18162470da26e6ae62ffcb7f0":{
      "scriptId":"u72"},
    "5b4abde060be4274826a914ea0d7e8a0":{
      "scriptId":"u73"},
    "a32ff2d3335744c7a6cd00a4b5cb9ce9":{
      "scriptId":"u74"},
    "c6bd277986334c758bcf9ddaaad44ec3":{
      "scriptId":"u75"},
    "1bc32781987c43edb97d90a335951fcc":{
      "scriptId":"u76"},
    "3a7b330660b24847ab0fb979fcba053e":{
      "scriptId":"u77"},
    "65da3f6807d14d248894ba40d1f0914b":{
      "scriptId":"u78"},
    "26f7ebde365845319a9786a86d7d4578":{
      "scriptId":"u79"},
    "7cf3d68afa2a4414ba30d569f8333ec0":{
      "scriptId":"u80"},
    "3ee456fee3be4ef69b6946ce1f9c5854":{
      "scriptId":"u81"},
    "c280404aa4be4d79bf63fd083086d74b":{
      "scriptId":"u82"},
    "e711b83d756c45648534668d377b67fd":{
      "scriptId":"u83"},
    "c927780370a0440284ddf7ad44e65e8f":{
      "scriptId":"u84"},
    "80ae1977c0be4a7abbfc1ba7d06482f5":{
      "scriptId":"u85"},
    "97aba5c15a6b46f09765b1fba3c1fc5b":{
      "scriptId":"u86"},
    "ecd00336f0b64a06b19e966442ba9451":{
      "scriptId":"u87"},
    "47c71daf29f44431a3141cfc5666714c":{
      "scriptId":"u88"}}});