$axure.loadCurrentPage({
  "url":"产品套餐查看.html",
  "generationDate":new Date(1388979809628.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/系统登录默认页/bg.jpg",
    "width":1000,
    "height":750},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"a3039e279d15478285767c1729bd7915",
    "type":"Axure:Page",
    "name":"产品套餐查看",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0a48a0b949aa46d38c916047df35dad0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":162},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c9dedbbca2e4a50bc8333c4bc70620d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":162},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品套餐管理",
                      "target":{
                        "targetType":"page",
                        "url":"产品套餐管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"910423d9287245b2a89eca24c9ff85bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":70},
            "size":{
              "width":152,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8647b7314596414584d2e3347bdb4c6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":70},
                "size":{
                  "width":152,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ce16e5068e4406aae91e2dec6184a32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":162},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0af6136ed5d4e7f91ac6dc731b6d60e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":162},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"266c306b4d354301848a6929a83e6420",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":214},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"366b70a58aaa4056a4a3eb493cee5b97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":214},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"986b7ea552be4a23938d7640be6fdd84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":259},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90002566765f43ecb798a31055548d31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":259},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1eb186a52ee641da97c912696465650b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":303},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64b230af7afc488abd74246d30224e1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":303},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc2b81b8e09944928a10fc524ca00aa0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":346},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a42577418874c5cb271862b0adef156",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":346},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8cee3683fdd143c9b662c49f1e371742",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":389},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6560b83cdf340a6af123dfb135170ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":389},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e54f6dbf612a4aa7a5d286448b3b6ced",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":432},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"892a1bd167414a67a15ec7cc1ffd54eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":432},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b9fb585cfc54997b7ccd205b8186908",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":564},
            "size":{
              "width":40,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c4ac4e7e8a74b3db59b0060bda90a18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":564},
                "size":{
                  "width":40,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41d7202914f54d76989b4ba6d7572416",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":471,
              "y":580},
            "size":{
              "width":170,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b1812e4cca9493f8de22ab916ce4f64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":471,
                  "y":580},
                "size":{
                  "width":170,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d727ee4c34d7421298f1ac703fc764c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xA5006600},
                "linePattern":"solid"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFDFEACA},
            "location":{
              "x":272,
              "y":636},
            "size":{
              "width":70,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF6DB847},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c90198cace654b5795e06209e78b3895",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xA5006600},
                    "linePattern":"solid"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDFEACA},
                "location":{
                  "x":272,
                  "y":636},
                "size":{
                  "width":70,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF6DB847},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品套餐管理",
                      "target":{
                        "targetType":"page",
                        "url":"产品套餐管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/公告详细页面/u57.png",
            "mouseOver~":"images/公告详细页面/u57_mouseOver.png"}},
{
          "id":"7e4bcb8473e54776963fb65c3fdce9c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":470},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a00fe5d1aa17409f94c084ea4aece571",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":470},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2af79e2a91e42b19cd6a97d028425d9",
          "label":"产品列表",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":451},
            "size":{
              "width":350,
              "height":82}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"778f94d8ec364c3a81d17b427e06f32e",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ae087750a2974c8194ee97757dd2c96e",
                  "label":"1",
                  "parentDynamicPanel":"c2af79e2a91e42b19cd6a97d028425d9",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":3,
                      "y":17},
                    "size":{
                      "width":281,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b6acfe380c4349bd958a71e3efe033d9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c2af79e2a91e42b19cd6a97d028425d9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":3,
                          "y":17},
                        "size":{
                          "width":281,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 新窗口/标签页 打开 产品详细",
                              "target":{
                                "targetType":"page",
                                "url":"产品详细.html",
                                "includeVariables":true},
                              "linkType":"new"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"86b10c08b3474970a53c21709cada2ea",
                  "label":"2",
                  "parentDynamicPanel":"c2af79e2a91e42b19cd6a97d028425d9",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":3,
                      "y":43},
                    "size":{
                      "width":281,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"448a7e6e89c440d5a5080ae36d1982a2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c2af79e2a91e42b19cd6a97d028425d9",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":3,
                          "y":43},
                        "size":{
                          "width":281,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"4b5f5594c5254427baa180c4d1f0d03b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":564},
            "size":{
              "width":341,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4aef6d716b0742cda385878b970e012a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":564},
                "size":{
                  "width":341,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8381ee390c104a68b4595c8bb5596ef3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":360,
              "y":214},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f20a8bcc0d7b4a8fb986bcb789517f84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":360,
                  "y":214},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"294b4957631947a8bc1c179b1db2f3f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":360,
              "y":259},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea9ded2f92b84ebb9560f4ea24c4626e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":360,
                  "y":259},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8650d0b1c5fd45d4b9c97a6ae271891a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":303},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ce826908f724a5ea4bcfa49fd0ae1fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":303},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"334a3b1566a143ef91639835ff0cb0d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":346},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"238f7d1683dd4c4ba839f658de68aa42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":346},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3122951dbb2f46f78b8ddb5b419409ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":389},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c2f980935314541b26c84a8a041ef55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":389},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9fd37cd52ac43888bcd2c3194bd6f58",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":432},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2d0ce5b81714309acf4202c82730dfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":432},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f29616a32bf42b5bd68d7e218c73934",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":271,
              "y":599},
            "size":{
              "width":640,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/产品套餐查看/u45_line.png"}},
{
          "id":"9d26c9e108da431cb160289c6dda426a",
          "label":"菜单",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":170},
            "size":{
              "width":141,
              "height":520}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"b1c893d679164adc9ffb69ef74c6d8a5",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"62697c253e3242deb2b8b47f6b366732",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":10}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"deb2444574e64b3ca01c03b1fe269ebe",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":18},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b7b171de1af34fe782450d5d8dfd13b7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":18},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f1680d62a281449792dd5229dbbefd25",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":236}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"94666952eacf493eb4bb441464bb9bc1",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":244},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"da97e2109a3f4690b597c0b92426803c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":244},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 注册新会员",
                              "target":{
                                "targetType":"page",
                                "url":"注册新会员.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9bebb678ed784e27a05f918b4f64de1d",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":269}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"7ca95da194484fae9123b22d42d02764",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":277},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"12ab19b0ce7248d18825f6b0512ba329",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":277},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 汇款充值",
                              "target":{
                                "targetType":"page",
                                "url":"汇款充值.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4ecffbb36db741b8a569fedcbe87d97e",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":302}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"29f6c2de473445bcbb25406f5c914cb5",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":310},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5462299e2b6249399dfdd110e8a97010",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":310},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 报单购物",
                              "target":{
                                "targetType":"page",
                                "url":"报单购物.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cc8a40baf2294d3b9f152ee693dfbb46",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":335}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"6aee1c31871940e9983d5335ffe1bd23",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":343},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a75e6a4f1404259abaa0fe6e1f2db3c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":343},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 奖励查询",
                              "target":{
                                "targetType":"page",
                                "url":"奖励查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"490ffba5ce9e4ad8abd1349786f518ac",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":368}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"256255662edd4435959fff8640bba265",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":376},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e215a2b927ab4235b24dc96c97ad71da",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":376},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b29342c0cfa14a11ae514f7fbce8d786",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":52},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dd2f3033c59a4e52b79c8517af816726",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":52},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cbf8023a7c4548adabbf1730ebeab29b",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":76},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"782733695b814b658b9ef9cc32f1af17",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":76},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 角色管理",
                              "target":{
                                "targetType":"page",
                                "url":"角色管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a4cc9fd9fd7d448ebf99a6da6245a299",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":102},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"549ec420707e4ed48641baa59aef682b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":102},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 权限管理",
                              "target":{
                                "targetType":"page",
                                "url":"权限管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a51e0f224f9e4b92a4f168b26212f3e8",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":125},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b6f3da9752eb45868001c5e7adff8a29",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":125},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 产品管理",
                              "target":{
                                "targetType":"page",
                                "url":"产品管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4612d8c29c7449288216a07539349cbb",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":150},
                    "size":{
                      "width":91,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9044f431e45a470abd18904bcdd8d472",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":150},
                        "size":{
                          "width":91,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 产品套餐管理",
                              "target":{
                                "targetType":"page",
                                "url":"产品套餐管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"64c6b13c6af54bc2bae315794ea4ba8b",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":174},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9c3c54a5ce4d4d758ffe9c869344c849",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":174},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 基础信息",
                              "target":{
                                "targetType":"page",
                                "url":"基础信息.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cfbc332a89be40ae9de9f16ebf6deff6",
                  "label":"",
                  "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":200},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"955fe1fbd7df4250babd6ef8b5a201a5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9d26c9e108da431cb160289c6dda426a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":200},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 数字字典",
                              "target":{
                                "targetType":"page",
                                "url":"数字字典.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"db0e433fd4cb45a59ab4c80dc5887595",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":300,
              "y":11},
            "size":{
              "width":178,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5940173e7e1249a38969920695e69ade",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":11},
                "size":{
                  "width":178,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f081c91701c540d282f157caf74e9e4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":488,
              "y":11},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e7678bed69643298486eb72e9d765b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":488,
                  "y":11},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3813c39eed546c8bc63057b8a5272cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":785,
              "y":11},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dff102b6f054d9ab8c0525450748c9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":785,
                  "y":11},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改本人密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改本人密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dec926b707a54c739b91233db80180e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":868,
              "y":11},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4d01a30209545a58c5c06be357a3eca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":868,
                  "y":11},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54fc73e647b04f8fa1aca8c611bf4586",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":617,
              "y":11},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"060387667ece4b559465d13c171d4b6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":617,
                  "y":11},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07ef91b8a6764474bc5224b67eef0897",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":11},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae3dc983241a41eba8b75718e0ef2975",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":708,
                  "y":11},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3037f51c835f4be0b339a0ae0a151c77",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":737,
              "y":11},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea7970077cf444a8ab2707566098f481",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":737,
                  "y":11},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u121.png"}},
{
          "id":"592d67a2e5f14e3b9676533deaf6a3f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":11},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8696e7db0464a13834ac9629af10216",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":11},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe187177d98a4251bbed3135a1dbf00d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":671,
              "y":11},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beba79f64c0c443795063837e5b905a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":671,
                  "y":11},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "d2415d04c3894ee2a19022d44e11f35b":{
      "packageId":"d2415d04c3894ee2a19022d44e11f35b",
      "type":"Axure:Master",
      "name":"nav",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7837bfaf60f741f3a6519b77012fd40a",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"7a89eecc0e584f76adbdcdcf2a6c58e7"}]}},
    "7a89eecc0e584f76adbdcdcf2a6c58e7":{
      "packageId":"7a89eecc0e584f76adbdcdcf2a6c58e7",
      "type":"Axure:Master",
      "name":"nav1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"82d5041198434b178bff196e00dfbfe6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":141,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7824ebb366034aba98ee9785a7394f11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":141,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统登录默认页/u13.jpg",
              "normal~":"images/系统登录默认页/u13.jpg",
              "normal~":"images/系统登录默认页/u13.jpg",
              "normal~":"images/系统登录默认页/u13.jpg",
              "normal~":"images/系统登录默认页/u13.jpg",
              "normal~":"images/系统登录默认页/u13.jpg"}}]}}},
  "objectPaths":{
    "0a48a0b949aa46d38c916047df35dad0":{
      "scriptId":"u0"},
    "6c9dedbbca2e4a50bc8333c4bc70620d":{
      "scriptId":"u1"},
    "910423d9287245b2a89eca24c9ff85bf":{
      "scriptId":"u2"},
    "8647b7314596414584d2e3347bdb4c6b":{
      "scriptId":"u3"},
    "2ce16e5068e4406aae91e2dec6184a32":{
      "scriptId":"u4"},
    "e0af6136ed5d4e7f91ac6dc731b6d60e":{
      "scriptId":"u5"},
    "266c306b4d354301848a6929a83e6420":{
      "scriptId":"u6"},
    "366b70a58aaa4056a4a3eb493cee5b97":{
      "scriptId":"u7"},
    "986b7ea552be4a23938d7640be6fdd84":{
      "scriptId":"u8"},
    "90002566765f43ecb798a31055548d31":{
      "scriptId":"u9"},
    "1eb186a52ee641da97c912696465650b":{
      "scriptId":"u10"},
    "64b230af7afc488abd74246d30224e1d":{
      "scriptId":"u11"},
    "cc2b81b8e09944928a10fc524ca00aa0":{
      "scriptId":"u12"},
    "5a42577418874c5cb271862b0adef156":{
      "scriptId":"u13"},
    "8cee3683fdd143c9b662c49f1e371742":{
      "scriptId":"u14"},
    "c6560b83cdf340a6af123dfb135170ea":{
      "scriptId":"u15"},
    "e54f6dbf612a4aa7a5d286448b3b6ced":{
      "scriptId":"u16"},
    "892a1bd167414a67a15ec7cc1ffd54eb":{
      "scriptId":"u17"},
    "8b9fb585cfc54997b7ccd205b8186908":{
      "scriptId":"u18"},
    "5c4ac4e7e8a74b3db59b0060bda90a18":{
      "scriptId":"u19"},
    "41d7202914f54d76989b4ba6d7572416":{
      "scriptId":"u20"},
    "5b1812e4cca9493f8de22ab916ce4f64":{
      "scriptId":"u21"},
    "d727ee4c34d7421298f1ac703fc764c4":{
      "scriptId":"u22"},
    "c90198cace654b5795e06209e78b3895":{
      "scriptId":"u23"},
    "7e4bcb8473e54776963fb65c3fdce9c0":{
      "scriptId":"u24"},
    "a00fe5d1aa17409f94c084ea4aece571":{
      "scriptId":"u25"},
    "c2af79e2a91e42b19cd6a97d028425d9":{
      "scriptId":"u26"},
    "ae087750a2974c8194ee97757dd2c96e":{
      "scriptId":"u27"},
    "b6acfe380c4349bd958a71e3efe033d9":{
      "scriptId":"u28"},
    "86b10c08b3474970a53c21709cada2ea":{
      "scriptId":"u29"},
    "448a7e6e89c440d5a5080ae36d1982a2":{
      "scriptId":"u30"},
    "4b5f5594c5254427baa180c4d1f0d03b":{
      "scriptId":"u31"},
    "4aef6d716b0742cda385878b970e012a":{
      "scriptId":"u32"},
    "8381ee390c104a68b4595c8bb5596ef3":{
      "scriptId":"u33"},
    "f20a8bcc0d7b4a8fb986bcb789517f84":{
      "scriptId":"u34"},
    "294b4957631947a8bc1c179b1db2f3f4":{
      "scriptId":"u35"},
    "ea9ded2f92b84ebb9560f4ea24c4626e":{
      "scriptId":"u36"},
    "8650d0b1c5fd45d4b9c97a6ae271891a":{
      "scriptId":"u37"},
    "4ce826908f724a5ea4bcfa49fd0ae1fe":{
      "scriptId":"u38"},
    "334a3b1566a143ef91639835ff0cb0d0":{
      "scriptId":"u39"},
    "238f7d1683dd4c4ba839f658de68aa42":{
      "scriptId":"u40"},
    "3122951dbb2f46f78b8ddb5b419409ab":{
      "scriptId":"u41"},
    "9c2f980935314541b26c84a8a041ef55":{
      "scriptId":"u42"},
    "b9fd37cd52ac43888bcd2c3194bd6f58":{
      "scriptId":"u43"},
    "c2d0ce5b81714309acf4202c82730dfa":{
      "scriptId":"u44"},
    "1f29616a32bf42b5bd68d7e218c73934":{
      "scriptId":"u45"},
    "9d26c9e108da431cb160289c6dda426a":{
      "scriptId":"u46"},
    "62697c253e3242deb2b8b47f6b366732":{
      "scriptId":"u47",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u48",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u49"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u50"}}},
    "deb2444574e64b3ca01c03b1fe269ebe":{
      "scriptId":"u51"},
    "b7b171de1af34fe782450d5d8dfd13b7":{
      "scriptId":"u52"},
    "f1680d62a281449792dd5229dbbefd25":{
      "scriptId":"u53",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u54",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u55"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u56"}}},
    "94666952eacf493eb4bb441464bb9bc1":{
      "scriptId":"u57"},
    "da97e2109a3f4690b597c0b92426803c":{
      "scriptId":"u58"},
    "9bebb678ed784e27a05f918b4f64de1d":{
      "scriptId":"u59",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u60",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u61"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u62"}}},
    "7ca95da194484fae9123b22d42d02764":{
      "scriptId":"u63"},
    "12ab19b0ce7248d18825f6b0512ba329":{
      "scriptId":"u64"},
    "4ecffbb36db741b8a569fedcbe87d97e":{
      "scriptId":"u65",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u66",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u67"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u68"}}},
    "29f6c2de473445bcbb25406f5c914cb5":{
      "scriptId":"u69"},
    "5462299e2b6249399dfdd110e8a97010":{
      "scriptId":"u70"},
    "cc8a40baf2294d3b9f152ee693dfbb46":{
      "scriptId":"u71",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u72",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u73"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u74"}}},
    "6aee1c31871940e9983d5335ffe1bd23":{
      "scriptId":"u75"},
    "7a75e6a4f1404259abaa0fe6e1f2db3c":{
      "scriptId":"u76"},
    "490ffba5ce9e4ad8abd1349786f518ac":{
      "scriptId":"u77",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u78",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u79"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u80"}}},
    "256255662edd4435959fff8640bba265":{
      "scriptId":"u81"},
    "e215a2b927ab4235b24dc96c97ad71da":{
      "scriptId":"u82"},
    "b29342c0cfa14a11ae514f7fbce8d786":{
      "scriptId":"u83"},
    "dd2f3033c59a4e52b79c8517af816726":{
      "scriptId":"u84"},
    "cbf8023a7c4548adabbf1730ebeab29b":{
      "scriptId":"u85"},
    "782733695b814b658b9ef9cc32f1af17":{
      "scriptId":"u86"},
    "a4cc9fd9fd7d448ebf99a6da6245a299":{
      "scriptId":"u87"},
    "549ec420707e4ed48641baa59aef682b":{
      "scriptId":"u88"},
    "a51e0f224f9e4b92a4f168b26212f3e8":{
      "scriptId":"u89"},
    "b6f3da9752eb45868001c5e7adff8a29":{
      "scriptId":"u90"},
    "4612d8c29c7449288216a07539349cbb":{
      "scriptId":"u91"},
    "9044f431e45a470abd18904bcdd8d472":{
      "scriptId":"u92"},
    "64c6b13c6af54bc2bae315794ea4ba8b":{
      "scriptId":"u93"},
    "9c3c54a5ce4d4d758ffe9c869344c849":{
      "scriptId":"u94"},
    "cfbc332a89be40ae9de9f16ebf6deff6":{
      "scriptId":"u95"},
    "955fe1fbd7df4250babd6ef8b5a201a5":{
      "scriptId":"u96"},
    "db0e433fd4cb45a59ab4c80dc5887595":{
      "scriptId":"u97"},
    "5940173e7e1249a38969920695e69ade":{
      "scriptId":"u98"},
    "f081c91701c540d282f157caf74e9e4b":{
      "scriptId":"u99"},
    "8e7678bed69643298486eb72e9d765b8":{
      "scriptId":"u100"},
    "a3813c39eed546c8bc63057b8a5272cc":{
      "scriptId":"u101"},
    "0dff102b6f054d9ab8c0525450748c9d":{
      "scriptId":"u102"},
    "dec926b707a54c739b91233db80180e2":{
      "scriptId":"u103"},
    "d4d01a30209545a58c5c06be357a3eca":{
      "scriptId":"u104"},
    "54fc73e647b04f8fa1aca8c611bf4586":{
      "scriptId":"u105"},
    "060387667ece4b559465d13c171d4b6f":{
      "scriptId":"u106"},
    "07ef91b8a6764474bc5224b67eef0897":{
      "scriptId":"u107"},
    "ae3dc983241a41eba8b75718e0ef2975":{
      "scriptId":"u108"},
    "3037f51c835f4be0b339a0ae0a151c77":{
      "scriptId":"u109"},
    "ea7970077cf444a8ab2707566098f481":{
      "scriptId":"u110"},
    "592d67a2e5f14e3b9676533deaf6a3f0":{
      "scriptId":"u111"},
    "c8696e7db0464a13834ac9629af10216":{
      "scriptId":"u112"},
    "fe187177d98a4251bbed3135a1dbf00d":{
      "scriptId":"u113"},
    "beba79f64c0c443795063837e5b905a8":{
      "scriptId":"u114"}}});