$axure.loadCurrentPage({
  "url":"产品详细.html",
  "generationDate":new Date(1388979807264.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/系统登录默认页/bg.jpg",
    "width":1000,
    "height":750},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"1384c1858cff48e7bfe601a31380efa7",
    "type":"Axure:Page",
    "name":"产品详细",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ab00b7b430bc4f76b07ca1a6be13c228",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":162},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccc7db06aba24fd2befb0813d3b2dd01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":162},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品管理",
                      "target":{
                        "targetType":"page",
                        "url":"产品管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c797c31ccc945898dfde75ccda75af6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":70},
            "size":{
              "width":152,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc47b243c1934396b05a7e93669bff63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":70},
                "size":{
                  "width":152,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de080d50613b4c489d395105c57bf01f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":317,
              "y":162},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"716a901cedfb40eba25623bfe48cb4f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":317,
                  "y":162},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab47ef186f6f476797d6281da7e17dfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":214},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0044aa3ec46478791b784862cb8ba7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":214},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ea524d1dfdf42639918b0983ce22d02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":259},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a5c0defdb3146f2b2e507bfdcfd57d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":259},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d9d0ed111f142c3abc4c3863b924377",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":303},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f7b99d65ac74254991b1262a6f99574",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":303},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf509dc5d04f4729baf2041898d6feb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":346},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"703e7cdf1b44447c80a31a87a094c111",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":346},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7c3f34b9b304e4e81220017dc58eebe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":389},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"938da07438574386b8d4ec7fb35f0fc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":389},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95f9c3ba0633474fb9d68e1668c898a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":432},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecba5dcaf0c847018369a04cab28f977",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":432},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bf7b922130847e0bb652d941a16d12b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":474},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd36b87039494aacadc0997e7c0a9bad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":474},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0146f53b591498588a4e3920e0dadbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":610},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efbcca15084443e5a830428b5fa66ba6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":610},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca759e56c4a24f589fa5b67c6abfdf5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":471,
              "y":580},
            "size":{
              "width":170,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1af443ed03e4348a6c33ab8fe98404c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":471,
                  "y":580},
                "size":{
                  "width":170,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b302ee5d1f5a48fcbe688bbe3be3f4e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xA5006600},
                "linePattern":"solid"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFDFEACA},
            "location":{
              "x":268,
              "y":696},
            "size":{
              "width":70,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF6DB847},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34d27bd884124040820c174208c5f9ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xA5006600},
                    "linePattern":"solid"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDFEACA},
                "location":{
                  "x":268,
                  "y":696},
                "size":{
                  "width":70,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF6DB847},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品管理",
                      "target":{
                        "targetType":"page",
                        "url":"产品管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/公告详细页面/u57.png",
            "mouseOver~":"images/公告详细页面/u57_mouseOver.png"}},
{
          "id":"68bfd0a789e44470b95b19882b93a6ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":360,
              "y":214},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ea40caa42a04acbb2a826af626861ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":360,
                  "y":214},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4dbaca529611417eb123da0784bf53dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":259},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"661843d8c365427681cb4e583f7697bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":368,
                  "y":259},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77e477e9883342169384f23b34459ab0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":360,
              "y":303},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0f3d202f7404a5f851d46bf75f70535",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":360,
                  "y":303},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c9f831d5bc54390b62e442b7470fcdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":360,
              "y":346},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61fffc9712b74c87b8ca1544170e165e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":360,
                  "y":346},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d6e369425024207b840c98e6eb5d92c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":389},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20e86e06e20d4eea97307953235d0962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":389},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26ffc9073d0949f081286f59e68e4b91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":474},
            "size":{
              "width":483,
              "height":94}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e62968215e34e17aeb955211a481fa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":474},
                "size":{
                  "width":483,
                  "height":94}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0c4f835de4c4085ab7d9bbbaf64b8c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":432},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"142ddbaa984c452b80474c2a2e4eae44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":432},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2b98101e45545e19205e08b234f93d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":610},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3d80ac5259c437fbecc1961fdd3d4fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":610},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c071c8b5f3d401cb54a7b93d78f6221",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":650},
            "size":{
              "width":639,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/产品详细/u42_line.png"}},
{
          "id":"2e067ebf9742418aaba1586430ddf8c5",
          "label":"菜单",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":170},
            "size":{
              "width":141,
              "height":520}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"dd399b09ec4644bea1c5f6e64c419faa",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"31699afa40de45888a2cb472c7756395",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":10}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"7f72032965934735996280cd11b2cffb",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":18},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6f170967343a4fd28e725b241bc6c2e7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":18},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9a605554abc041eb9e3d33e85c59c6b4",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":236}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"f96dad39f217488bbb870fe1e48ddfb0",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":244},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6fbbbffeb955417ab6925088484ce09c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":244},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 注册新会员",
                              "target":{
                                "targetType":"page",
                                "url":"注册新会员.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c2a4d755060247e790ddeb63c84e73bf",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":269}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"ed049a06f4024ddaa66afeeca52b176c",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":277},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"16df52869bbd479d9ee41a78d1369480",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":277},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 汇款充值",
                              "target":{
                                "targetType":"page",
                                "url":"汇款充值.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ab39391668084e16a1ba92c795eea0c7",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":302}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"d957505b064447efa2b2673286df5991",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":310},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"08bdf8d85f6d4a97955564966e21e2c2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":310},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 报单购物",
                              "target":{
                                "targetType":"page",
                                "url":"报单购物.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d32ca7cbf5ec432a8ec09a8e6ddd6da6",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":335}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"1b7104b831e44f2abeecd6b642750e08",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":343},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0abc6ba202ea42f8ba8dbb02cb6a709b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":343},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 奖励查询",
                              "target":{
                                "targetType":"page",
                                "url":"奖励查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"969c9b448e0c40f2b9f3d9f1d7cee9be",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":368}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"0c8ff2eff9894f2d920a509845dda052",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":376},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"849e94ac8cf1418fb8d2ed93e28d823b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":376},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"64a64f633b6047b8b6a16433d7bd40c0",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":52},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"79756e861edb4e968f13ba18cf7a3290",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":52},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c22dd1946477406a8642c48d59232822",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":76},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"968fae26984641829c27c29cb1bb675c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":76},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 角色管理",
                              "target":{
                                "targetType":"page",
                                "url":"角色管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0c14320bcde049f79d17f7e53bf16757",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":102},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ec9ef6ea31304e5bb190462ddcd07400",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":102},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 权限管理",
                              "target":{
                                "targetType":"page",
                                "url":"权限管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c072416e120b4c6e8f1345496f6ea88a",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":125},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c5ad642961040e7be7241ba2f5d8ad2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":125},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 产品管理",
                              "target":{
                                "targetType":"page",
                                "url":"产品管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"dd9ad187ceff4ababa433d637bb1b700",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":150},
                    "size":{
                      "width":91,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"71771f8224c5456ca61c9972f4fca16c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":150},
                        "size":{
                          "width":91,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 产品套餐管理",
                              "target":{
                                "targetType":"page",
                                "url":"产品套餐管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d6ad88465c064510bc1bcfb5355fef54",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":174},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6b93691cfbbc4ceebae99636ea250ee2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":174},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 基础信息",
                              "target":{
                                "targetType":"page",
                                "url":"基础信息.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5b387d5e62ec4785b8d69714f6bde5c2",
                  "label":"",
                  "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":200},
                    "size":{
                      "width":65,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4e9758cd1b8d4b8690de7366f2202efd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2e067ebf9742418aaba1586430ddf8c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":200},
                        "size":{
                          "width":65,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 数字字典",
                              "target":{
                                "targetType":"page",
                                "url":"数字字典.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"26976f8f5f4945ee93a1f156fbb8dad2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":300,
              "y":11},
            "size":{
              "width":178,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fa9fa7b73014be1837bd58b9f9e9ec9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":11},
                "size":{
                  "width":178,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3f01b2702b74b06993bfb30060683d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":488,
              "y":11},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf84f705d72348f0aff8bba42a8920d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":488,
                  "y":11},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"992e854959244d56bdd9ff0b4ad51229",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":785,
              "y":11},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13aca7d34a4a42a69744406db434deba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":785,
                  "y":11},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改本人密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改本人密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2026e716ad474cf883f161bbfba0f343",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":868,
              "y":11},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54e6bb9331de4b7ca20b6919735a9630",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":868,
                  "y":11},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a620a959b7ba47f083bc36eb637e0970",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":617,
              "y":11},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4570e9f3b5a54713a4fa7ba14d01fa22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":617,
                  "y":11},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"edf2cb1b52dd4fb793fa8bb3c011fc13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":11},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99b969ed3c154dcca215721f798754c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":708,
                  "y":11},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2f7a615ba9a4b02864910c7feede602",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":737,
              "y":11},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e714fbd0679649de974fbc0bece196c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":737,
                  "y":11},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u121.png"}},
{
          "id":"9e29ca882ab94bff8754c8c2e83ae440",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":11},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"465e80f52ba444e4a27f73ae909470c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":11},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"310806e87647440f9f01ebf699a0e7d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":671,
              "y":11},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1754ff9d1024eb88747e5ba01092135",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":671,
                  "y":11},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "d2415d04c3894ee2a19022d44e11f35b":{
      "packageId":"d2415d04c3894ee2a19022d44e11f35b",
      "type":"Axure:Master",
      "name":"nav",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7837bfaf60f741f3a6519b77012fd40a",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"7a89eecc0e584f76adbdcdcf2a6c58e7"}]}},
    "7a89eecc0e584f76adbdcdcf2a6c58e7":{
      "packageId":"7a89eecc0e584f76adbdcdcf2a6c58e7",
      "type":"Axure:Master",
      "name":"nav1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"82d5041198434b178bff196e00dfbfe6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":141,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7824ebb366034aba98ee9785a7394f11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":141,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统登录默认页/u13.jpg",
              "normal~":"images/系统登录默认页/u13.jpg",
              "normal~":"images/系统登录默认页/u13.jpg",
              "normal~":"images/系统登录默认页/u13.jpg",
              "normal~":"images/系统登录默认页/u13.jpg",
              "normal~":"images/系统登录默认页/u13.jpg"}}]}}},
  "objectPaths":{
    "ab00b7b430bc4f76b07ca1a6be13c228":{
      "scriptId":"u0"},
    "ccc7db06aba24fd2befb0813d3b2dd01":{
      "scriptId":"u1"},
    "5c797c31ccc945898dfde75ccda75af6":{
      "scriptId":"u2"},
    "bc47b243c1934396b05a7e93669bff63":{
      "scriptId":"u3"},
    "de080d50613b4c489d395105c57bf01f":{
      "scriptId":"u4"},
    "716a901cedfb40eba25623bfe48cb4f5":{
      "scriptId":"u5"},
    "ab47ef186f6f476797d6281da7e17dfb":{
      "scriptId":"u6"},
    "c0044aa3ec46478791b784862cb8ba7b":{
      "scriptId":"u7"},
    "6ea524d1dfdf42639918b0983ce22d02":{
      "scriptId":"u8"},
    "2a5c0defdb3146f2b2e507bfdcfd57d6":{
      "scriptId":"u9"},
    "5d9d0ed111f142c3abc4c3863b924377":{
      "scriptId":"u10"},
    "1f7b99d65ac74254991b1262a6f99574":{
      "scriptId":"u11"},
    "cf509dc5d04f4729baf2041898d6feb3":{
      "scriptId":"u12"},
    "703e7cdf1b44447c80a31a87a094c111":{
      "scriptId":"u13"},
    "c7c3f34b9b304e4e81220017dc58eebe":{
      "scriptId":"u14"},
    "938da07438574386b8d4ec7fb35f0fc6":{
      "scriptId":"u15"},
    "95f9c3ba0633474fb9d68e1668c898a5":{
      "scriptId":"u16"},
    "ecba5dcaf0c847018369a04cab28f977":{
      "scriptId":"u17"},
    "9bf7b922130847e0bb652d941a16d12b":{
      "scriptId":"u18"},
    "bd36b87039494aacadc0997e7c0a9bad":{
      "scriptId":"u19"},
    "b0146f53b591498588a4e3920e0dadbb":{
      "scriptId":"u20"},
    "efbcca15084443e5a830428b5fa66ba6":{
      "scriptId":"u21"},
    "ca759e56c4a24f589fa5b67c6abfdf5e":{
      "scriptId":"u22"},
    "a1af443ed03e4348a6c33ab8fe98404c":{
      "scriptId":"u23"},
    "b302ee5d1f5a48fcbe688bbe3be3f4e3":{
      "scriptId":"u24"},
    "34d27bd884124040820c174208c5f9ae":{
      "scriptId":"u25"},
    "68bfd0a789e44470b95b19882b93a6ff":{
      "scriptId":"u26"},
    "3ea40caa42a04acbb2a826af626861ea":{
      "scriptId":"u27"},
    "4dbaca529611417eb123da0784bf53dc":{
      "scriptId":"u28"},
    "661843d8c365427681cb4e583f7697bc":{
      "scriptId":"u29"},
    "77e477e9883342169384f23b34459ab0":{
      "scriptId":"u30"},
    "d0f3d202f7404a5f851d46bf75f70535":{
      "scriptId":"u31"},
    "2c9f831d5bc54390b62e442b7470fcdf":{
      "scriptId":"u32"},
    "61fffc9712b74c87b8ca1544170e165e":{
      "scriptId":"u33"},
    "0d6e369425024207b840c98e6eb5d92c":{
      "scriptId":"u34"},
    "20e86e06e20d4eea97307953235d0962":{
      "scriptId":"u35"},
    "26ffc9073d0949f081286f59e68e4b91":{
      "scriptId":"u36"},
    "0e62968215e34e17aeb955211a481fa5":{
      "scriptId":"u37"},
    "d0c4f835de4c4085ab7d9bbbaf64b8c0":{
      "scriptId":"u38"},
    "142ddbaa984c452b80474c2a2e4eae44":{
      "scriptId":"u39"},
    "a2b98101e45545e19205e08b234f93d3":{
      "scriptId":"u40"},
    "c3d80ac5259c437fbecc1961fdd3d4fd":{
      "scriptId":"u41"},
    "0c071c8b5f3d401cb54a7b93d78f6221":{
      "scriptId":"u42"},
    "2e067ebf9742418aaba1586430ddf8c5":{
      "scriptId":"u43"},
    "31699afa40de45888a2cb472c7756395":{
      "scriptId":"u44",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u45",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u46"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u47"}}},
    "7f72032965934735996280cd11b2cffb":{
      "scriptId":"u48"},
    "6f170967343a4fd28e725b241bc6c2e7":{
      "scriptId":"u49"},
    "9a605554abc041eb9e3d33e85c59c6b4":{
      "scriptId":"u50",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u51",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u52"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u53"}}},
    "f96dad39f217488bbb870fe1e48ddfb0":{
      "scriptId":"u54"},
    "6fbbbffeb955417ab6925088484ce09c":{
      "scriptId":"u55"},
    "c2a4d755060247e790ddeb63c84e73bf":{
      "scriptId":"u56",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u57",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u58"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u59"}}},
    "ed049a06f4024ddaa66afeeca52b176c":{
      "scriptId":"u60"},
    "16df52869bbd479d9ee41a78d1369480":{
      "scriptId":"u61"},
    "ab39391668084e16a1ba92c795eea0c7":{
      "scriptId":"u62",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u63",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u64"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u65"}}},
    "d957505b064447efa2b2673286df5991":{
      "scriptId":"u66"},
    "08bdf8d85f6d4a97955564966e21e2c2":{
      "scriptId":"u67"},
    "d32ca7cbf5ec432a8ec09a8e6ddd6da6":{
      "scriptId":"u68",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u69",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u70"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u71"}}},
    "1b7104b831e44f2abeecd6b642750e08":{
      "scriptId":"u72"},
    "0abc6ba202ea42f8ba8dbb02cb6a709b":{
      "scriptId":"u73"},
    "969c9b448e0c40f2b9f3d9f1d7cee9be":{
      "scriptId":"u74",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u75",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u76"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u77"}}},
    "0c8ff2eff9894f2d920a509845dda052":{
      "scriptId":"u78"},
    "849e94ac8cf1418fb8d2ed93e28d823b":{
      "scriptId":"u79"},
    "64a64f633b6047b8b6a16433d7bd40c0":{
      "scriptId":"u80"},
    "79756e861edb4e968f13ba18cf7a3290":{
      "scriptId":"u81"},
    "c22dd1946477406a8642c48d59232822":{
      "scriptId":"u82"},
    "968fae26984641829c27c29cb1bb675c":{
      "scriptId":"u83"},
    "0c14320bcde049f79d17f7e53bf16757":{
      "scriptId":"u84"},
    "ec9ef6ea31304e5bb190462ddcd07400":{
      "scriptId":"u85"},
    "c072416e120b4c6e8f1345496f6ea88a":{
      "scriptId":"u86"},
    "2c5ad642961040e7be7241ba2f5d8ad2":{
      "scriptId":"u87"},
    "dd9ad187ceff4ababa433d637bb1b700":{
      "scriptId":"u88"},
    "71771f8224c5456ca61c9972f4fca16c":{
      "scriptId":"u89"},
    "d6ad88465c064510bc1bcfb5355fef54":{
      "scriptId":"u90"},
    "6b93691cfbbc4ceebae99636ea250ee2":{
      "scriptId":"u91"},
    "5b387d5e62ec4785b8d69714f6bde5c2":{
      "scriptId":"u92"},
    "4e9758cd1b8d4b8690de7366f2202efd":{
      "scriptId":"u93"},
    "26976f8f5f4945ee93a1f156fbb8dad2":{
      "scriptId":"u94"},
    "4fa9fa7b73014be1837bd58b9f9e9ec9":{
      "scriptId":"u95"},
    "e3f01b2702b74b06993bfb30060683d4":{
      "scriptId":"u96"},
    "cf84f705d72348f0aff8bba42a8920d6":{
      "scriptId":"u97"},
    "992e854959244d56bdd9ff0b4ad51229":{
      "scriptId":"u98"},
    "13aca7d34a4a42a69744406db434deba":{
      "scriptId":"u99"},
    "2026e716ad474cf883f161bbfba0f343":{
      "scriptId":"u100"},
    "54e6bb9331de4b7ca20b6919735a9630":{
      "scriptId":"u101"},
    "a620a959b7ba47f083bc36eb637e0970":{
      "scriptId":"u102"},
    "4570e9f3b5a54713a4fa7ba14d01fa22":{
      "scriptId":"u103"},
    "edf2cb1b52dd4fb793fa8bb3c011fc13":{
      "scriptId":"u104"},
    "99b969ed3c154dcca215721f798754c1":{
      "scriptId":"u105"},
    "a2f7a615ba9a4b02864910c7feede602":{
      "scriptId":"u106"},
    "e714fbd0679649de974fbc0bece196c6":{
      "scriptId":"u107"},
    "9e29ca882ab94bff8754c8c2e83ae440":{
      "scriptId":"u108"},
    "465e80f52ba444e4a27f73ae909470c3":{
      "scriptId":"u109"},
    "310806e87647440f9f01ebf699a0e7d8":{
      "scriptId":"u110"},
    "b1754ff9d1024eb88747e5ba01092135":{
      "scriptId":"u111"}}});