$axure.loadCurrentPage({
  "url":"注册新会员.html",
  "generationDate":new Date(1383038955055.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/系统登录默认页/bg.jpg",
    "width":1000,
    "height":750},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"c9b99e4efd284a1b9a2ced53112f2b1b",
    "type":"Axure:Page",
    "name":"注册新会员",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"356eefa0bfe2467a9da15de21957b846",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":162},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b517ea3f46f469183ed9b7554294943",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":162},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65f59615714840588c2684ebedc2b24f",
          "label":"菜单",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":170},
            "size":{
              "width":141,
              "height":520}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"351d6aca07db4d2695a4ebcdfd8817cc",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"05ece5410d804b6a859bb09c5955bcc9",
                  "label":"",
                  "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":10}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"6972feb979e84cfca0f2d0e38f11d502",
                  "label":"",
                  "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":18},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7556527b25134a21b2aa7ad9db875482",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":18},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d2bdf2d7d7654fb290bd0fd40dd7bfd2",
                  "label":"",
                  "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":43}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"ce93b1ea4aaf4ce4aa7274ba536f82df",
                  "label":"",
                  "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":51},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a91c67d8d2146378d58cc5482b787df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":51},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 注册新会员",
                              "target":{
                                "targetType":"page",
                                "url":"注册新会员.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9e2399179de74848a25d7657274120d8",
                  "label":"",
                  "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":176},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"772a2d4bddfb45faa569caf0fecac064",
                  "label":"",
                  "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":184},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5bbacb627063459fbd1b6b4ca25fe5f5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":184},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 汇款充值",
                              "target":{
                                "targetType":"page",
                                "url":"汇款充值.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"18976e2544a14f6eb9ecb6b898f9d860",
                  "label":"",
                  "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":209},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"b4794b10073d423d85475f33adf8d889",
                  "label":"",
                  "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":217},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"79838238ea9d472b86fd24eea03c60bf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":217},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 报单购物",
                              "target":{
                                "targetType":"page",
                                "url":"报单购物.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"03cb225bebc643dbab0f01f3e2707b42",
                  "label":"",
                  "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":242},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"7a57beb9d2bd4871b82c6ff1915dc65c",
                  "label":"",
                  "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":250},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bc5b66f1d2df4abc9a2c44d4c4153b61",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":250},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 奖励查询",
                              "target":{
                                "targetType":"page",
                                "url":"奖励查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b5187b80b5d044f29de1cf0979283413",
                  "label":"",
                  "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":275},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"23d82d80b2fa4605af3fdc82dfaae842",
                  "label":"",
                  "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":283},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2d56ec9a217040f5b7fa74a7136395b5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":283},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"05c5a59c0c284030ac5ebac704867c21",
                  "label":"",
                  "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00,
                      "opacity":1},
                    "location":{
                      "x":31,
                      "y":85},
                    "size":{
                      "width":78,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"be5df8ffb582420fb642fb6cbdb09965",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00,
                          "opacity":1},
                        "location":{
                          "x":31,
                          "y":85},
                        "size":{
                          "width":78,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 注册新会员",
                              "target":{
                                "targetType":"page",
                                "url":"注册新会员.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5b838f7e564345b7b74e040aa1e85d74",
                  "label":"",
                  "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":107},
                    "size":{
                      "width":78,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e6965d784336463c9074ee1a72567d54",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":107},
                        "size":{
                          "width":78,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 新会员管理",
                              "target":{
                                "targetType":"page",
                                "url":"新会员管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6b44de075ce242669e30b71fb132f0d8",
                  "label":"",
                  "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":129},
                    "size":{
                      "width":91,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9cf876307235432e9ba5323006b06ccf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":129},
                        "size":{
                          "width":91,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 修改本人资料",
                              "target":{
                                "targetType":"page",
                                "url":"修改本人资料.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3528d0ed343c40638315ba8a0d54845c",
                  "label":"",
                  "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":150},
                    "size":{
                      "width":91,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ec5d793193814a21ac081e1a93b5c2da",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65f59615714840588c2684ebedc2b24f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":150},
                        "size":{
                          "width":91,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 修改本人密码",
                              "target":{
                                "targetType":"page",
                                "url":"修改本人密码.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"0bd7de57d3684750ae0d9f872e0bd63e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":70},
            "size":{
              "width":152,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ed749d1ff1e4f61bba57302090c2d18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":70},
                "size":{
                  "width":152,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2568e4235ea94a279542ca596f5068f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":162},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17ba569ebb8045b3a39be58a60cfa83a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":162},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a21b94a6b7a44b6ca4b32a26e496eefc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":241,
              "y":370},
            "size":{
              "width":670,
              "height":667}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"403f2fbbc6a94756b274029e8fe90fef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":241,
                  "y":370},
                "size":{
                  "width":670,
                  "height":667}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39b4bcda7f1d463ba212d6184af95227",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":659,
              "y":1047},
            "size":{
              "width":171,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af0af17c4b3b467e95bdd73c051d8c41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":659,
                  "y":1047},
                "size":{
                  "width":171,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]},
{
                      "action":"setPanelState",
                      "description":"设置 xiayibu 到 2",
                      "panelsToStates":[{
                          "panelPath":["fbc942cf87074bebbddb70a7092293ea"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}}},
{
          "id":"fbc942cf87074bebbddb70a7092293ea",
          "label":"xiayibu",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":1030},
            "size":{
              "width":140,
              "height":50}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c3ba6b606a584163bdc688dd7f23b61f",
              "label":"1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1991a38650114dc69d574209a093db0d",
                  "label":"",
                  "parentDynamicPanel":"fbc942cf87074bebbddb70a7092293ea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xA5006600},
                        "linePattern":"solid"}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFDFEACA},
                    "location":{
                      "x":20,
                      "y":16},
                    "size":{
                      "width":100,
                      "height":24},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF6DB847},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a10f5b54f235482594380cc94251e11f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fbc942cf87074bebbddb70a7092293ea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xA5006600},
                            "linePattern":"solid"}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDFEACA},
                        "location":{
                          "x":20,
                          "y":16},
                        "size":{
                          "width":100,
                          "height":24},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF6DB847},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/注册新会员/u56.png",
                    "mouseOver~":"images/注册新会员/u56_mouseOver.png"}}]},
{
              "id":"0ce5746b1bfd44c6b8ab01f93834e7d1",
              "label":"2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"77efef2a652b4ca99303bc62b995a454",
                  "label":"",
                  "parentDynamicPanel":"fbc942cf87074bebbddb70a7092293ea",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xA5006600},
                        "linePattern":"solid"}},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFDFEACA},
                    "location":{
                      "x":20,
                      "y":16},
                    "size":{
                      "width":100,
                      "height":24},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF6DB847},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f961202b30f1405faf73fc4177da9d10",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"fbc942cf87074bebbddb70a7092293ea",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xA5006600},
                            "linePattern":"solid"}},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDFEACA},
                        "location":{
                          "x":20,
                          "y":16},
                        "size":{
                          "width":100,
                          "height":24},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF6DB847},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 注册表单",
                              "target":{
                                "targetType":"page",
                                "url":"注册表单.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/注册新会员/u56.png",
                    "mouseOver~":"images/注册新会员/u56_mouseOver.png"}}]}]},
{
          "id":"1454b33ca44545be8a8b88cd6147ba96",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":241,
              "y":196},
            "size":{
              "width":659,
              "height":134}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"658706ee60004bfa93f6ad1ce05605b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":241,
                  "y":196},
                "size":{
                  "width":659,
                  "height":134}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36d4803a12a94f31bd1e1b50792e1e5a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":241,
              "y":350},
            "size":{
              "width":670,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册新会员/u62_line.png"}},
{
          "id":"8b0737b352cb4be281d9ac9218573614",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":241,
              "y":334},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e55e73b494e04910ae33705196019cf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":241,
                  "y":334},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1616a25814ce467f842a8ef7b8297804",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":306,
              "y":15},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc83e8c9b8574af0af5df76ffbf0a0e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":15},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"279076ab25554b7a9722fd748d58f701",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":408,
              "y":15},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e17122eba2242b58df8f90bff45d182",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":408,
                  "y":15},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02690695fd2b4274ad19cdbc5cfb6a98",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":785,
              "y":15},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e69a13ef8ee148f9b4c17dc98316ccdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":785,
                  "y":15},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改本人密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改本人密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7cbec82329634836bb9a1836c08440f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":868,
              "y":15},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc2b88bc03ba458f97fc60ef37e09a00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":868,
                  "y":15},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86c0d4707f0140c592c36a203270be3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":617,
              "y":15},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e86c30ed53ad4206bae9b2894cdd6a06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":617,
                  "y":15},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b360f22d3234fa29b7b1433824afa3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":15},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32c3ee7fb6704f95bdaa79f280f2a867",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":708,
                  "y":15},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb9f7def2aab4fa8ae0f5553b656ff6e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":737,
              "y":15},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28d8450fbef94a659ded5952477ed164",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":737,
                  "y":15},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u121.png"}},
{
          "id":"767c297676064bf9855502c123443025",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":15},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19a8bfc63d7247ffb5a50ab1d66a2ed6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":15},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ecc4330f9404e74b7376b8805881f36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":671,
              "y":15},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a60ccbd2b88c4f0fbaa6e4fab735795f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":671,
                  "y":15},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d65c0b5cc18a4a05b727ad5bccc2bd80",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":526,
              "y":14},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"791d510e4cc2457d95cf3048a5f7a97a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":526,
                  "y":14},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 购物车",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u127.png"}},
{
          "id":"294946b4026f4813b2e657cdffb5239a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":3},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c55db77b372546c9921646a0c0e35928",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":542,
                  "y":3},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/系统登录默认页/u129.png"}},
{
          "id":"eb8323aeafc44e98a0bc79f52bf0dbd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":547,
              "y":1},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"963d40de88ed4829b2ec73b37c76291b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":547,
                  "y":1},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "d2415d04c3894ee2a19022d44e11f35b":{
      "packageId":"d2415d04c3894ee2a19022d44e11f35b",
      "type":"Axure:Master",
      "name":"nav",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7837bfaf60f741f3a6519b77012fd40a",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"7a89eecc0e584f76adbdcdcf2a6c58e7"}]}},
    "7a89eecc0e584f76adbdcdcf2a6c58e7":{
      "packageId":"7a89eecc0e584f76adbdcdcf2a6c58e7",
      "type":"Axure:Master",
      "name":"nav1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"82d5041198434b178bff196e00dfbfe6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":141,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7824ebb366034aba98ee9785a7394f11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":141,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg"}}]}}},
  "objectPaths":{
    "356eefa0bfe2467a9da15de21957b846":{
      "scriptId":"u0"},
    "8b517ea3f46f469183ed9b7554294943":{
      "scriptId":"u1"},
    "65f59615714840588c2684ebedc2b24f":{
      "scriptId":"u2"},
    "05ece5410d804b6a859bb09c5955bcc9":{
      "scriptId":"u3",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u4",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u5"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u6"}}},
    "6972feb979e84cfca0f2d0e38f11d502":{
      "scriptId":"u7"},
    "7556527b25134a21b2aa7ad9db875482":{
      "scriptId":"u8"},
    "d2bdf2d7d7654fb290bd0fd40dd7bfd2":{
      "scriptId":"u9",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u10",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u11"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u12"}}},
    "ce93b1ea4aaf4ce4aa7274ba536f82df":{
      "scriptId":"u13"},
    "4a91c67d8d2146378d58cc5482b787df":{
      "scriptId":"u14"},
    "9e2399179de74848a25d7657274120d8":{
      "scriptId":"u15",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u16",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u17"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u18"}}},
    "772a2d4bddfb45faa569caf0fecac064":{
      "scriptId":"u19"},
    "5bbacb627063459fbd1b6b4ca25fe5f5":{
      "scriptId":"u20"},
    "18976e2544a14f6eb9ecb6b898f9d860":{
      "scriptId":"u21",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u22",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u23"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u24"}}},
    "b4794b10073d423d85475f33adf8d889":{
      "scriptId":"u25"},
    "79838238ea9d472b86fd24eea03c60bf":{
      "scriptId":"u26"},
    "03cb225bebc643dbab0f01f3e2707b42":{
      "scriptId":"u27",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u28",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u29"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u30"}}},
    "7a57beb9d2bd4871b82c6ff1915dc65c":{
      "scriptId":"u31"},
    "bc5b66f1d2df4abc9a2c44d4c4153b61":{
      "scriptId":"u32"},
    "b5187b80b5d044f29de1cf0979283413":{
      "scriptId":"u33",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u34",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u35"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u36"}}},
    "23d82d80b2fa4605af3fdc82dfaae842":{
      "scriptId":"u37"},
    "2d56ec9a217040f5b7fa74a7136395b5":{
      "scriptId":"u38"},
    "05c5a59c0c284030ac5ebac704867c21":{
      "scriptId":"u39"},
    "be5df8ffb582420fb642fb6cbdb09965":{
      "scriptId":"u40"},
    "5b838f7e564345b7b74e040aa1e85d74":{
      "scriptId":"u41"},
    "e6965d784336463c9074ee1a72567d54":{
      "scriptId":"u42"},
    "6b44de075ce242669e30b71fb132f0d8":{
      "scriptId":"u43"},
    "9cf876307235432e9ba5323006b06ccf":{
      "scriptId":"u44"},
    "3528d0ed343c40638315ba8a0d54845c":{
      "scriptId":"u45"},
    "ec5d793193814a21ac081e1a93b5c2da":{
      "scriptId":"u46"},
    "0bd7de57d3684750ae0d9f872e0bd63e":{
      "scriptId":"u47"},
    "5ed749d1ff1e4f61bba57302090c2d18":{
      "scriptId":"u48"},
    "2568e4235ea94a279542ca596f5068f4":{
      "scriptId":"u49"},
    "17ba569ebb8045b3a39be58a60cfa83a":{
      "scriptId":"u50"},
    "a21b94a6b7a44b6ca4b32a26e496eefc":{
      "scriptId":"u51"},
    "403f2fbbc6a94756b274029e8fe90fef":{
      "scriptId":"u52"},
    "39b4bcda7f1d463ba212d6184af95227":{
      "scriptId":"u53"},
    "af0af17c4b3b467e95bdd73c051d8c41":{
      "scriptId":"u54"},
    "fbc942cf87074bebbddb70a7092293ea":{
      "scriptId":"u55"},
    "1991a38650114dc69d574209a093db0d":{
      "scriptId":"u56"},
    "a10f5b54f235482594380cc94251e11f":{
      "scriptId":"u57"},
    "77efef2a652b4ca99303bc62b995a454":{
      "scriptId":"u58"},
    "f961202b30f1405faf73fc4177da9d10":{
      "scriptId":"u59"},
    "1454b33ca44545be8a8b88cd6147ba96":{
      "scriptId":"u60"},
    "658706ee60004bfa93f6ad1ce05605b6":{
      "scriptId":"u61"},
    "36d4803a12a94f31bd1e1b50792e1e5a":{
      "scriptId":"u62"},
    "8b0737b352cb4be281d9ac9218573614":{
      "scriptId":"u63"},
    "e55e73b494e04910ae33705196019cf2":{
      "scriptId":"u64"},
    "1616a25814ce467f842a8ef7b8297804":{
      "scriptId":"u65"},
    "dc83e8c9b8574af0af5df76ffbf0a0e1":{
      "scriptId":"u66"},
    "279076ab25554b7a9722fd748d58f701":{
      "scriptId":"u67"},
    "3e17122eba2242b58df8f90bff45d182":{
      "scriptId":"u68"},
    "02690695fd2b4274ad19cdbc5cfb6a98":{
      "scriptId":"u69"},
    "e69a13ef8ee148f9b4c17dc98316ccdc":{
      "scriptId":"u70"},
    "7cbec82329634836bb9a1836c08440f9":{
      "scriptId":"u71"},
    "cc2b88bc03ba458f97fc60ef37e09a00":{
      "scriptId":"u72"},
    "86c0d4707f0140c592c36a203270be3b":{
      "scriptId":"u73"},
    "e86c30ed53ad4206bae9b2894cdd6a06":{
      "scriptId":"u74"},
    "4b360f22d3234fa29b7b1433824afa3f":{
      "scriptId":"u75"},
    "32c3ee7fb6704f95bdaa79f280f2a867":{
      "scriptId":"u76"},
    "fb9f7def2aab4fa8ae0f5553b656ff6e":{
      "scriptId":"u77"},
    "28d8450fbef94a659ded5952477ed164":{
      "scriptId":"u78"},
    "767c297676064bf9855502c123443025":{
      "scriptId":"u79"},
    "19a8bfc63d7247ffb5a50ab1d66a2ed6":{
      "scriptId":"u80"},
    "8ecc4330f9404e74b7376b8805881f36":{
      "scriptId":"u81"},
    "a60ccbd2b88c4f0fbaa6e4fab735795f":{
      "scriptId":"u82"},
    "d65c0b5cc18a4a05b727ad5bccc2bd80":{
      "scriptId":"u83"},
    "791d510e4cc2457d95cf3048a5f7a97a":{
      "scriptId":"u84"},
    "294946b4026f4813b2e657cdffb5239a":{
      "scriptId":"u85"},
    "c55db77b372546c9921646a0c0e35928":{
      "scriptId":"u86"},
    "eb8323aeafc44e98a0bc79f52bf0dbd3":{
      "scriptId":"u87"},
    "963d40de88ed4829b2ec73b37c76291b":{
      "scriptId":"u88"}}});