$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1383038947699.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/登录/bg.jpg",
    "width":1014,
    "height":617},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"2128c3501dd54642a5bd9acaa88b66f8",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f982d98dcb714f3cba58cb8af3033d82",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":715,
              "y":295},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"ef26c5a45e1144ae916f0d74e33d13f4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":832,
              "y":295},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"32c704b0438d45279c62010912e86560",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":292},
            "size":{
              "width":160,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"4f1b8d17e6544a909c6b924282b71992",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":545,
              "y":292},
            "size":{
              "width":145,
              "height":28}},
          "adaptiveStyles":{
}},
{
          "id":"80f64dddc4d24bec90e09cafdb760ca7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":730,
              "y":299},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f5e1e5f09c5439d9b3145a5b239ff24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":730,
                  "y":299},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f982d98dcb714f3cba58cb8af3033d82":{
      "scriptId":"u0"},
    "ef26c5a45e1144ae916f0d74e33d13f4":{
      "scriptId":"u1"},
    "32c704b0438d45279c62010912e86560":{
      "scriptId":"u2"},
    "4f1b8d17e6544a909c6b924282b71992":{
      "scriptId":"u3"},
    "80f64dddc4d24bec90e09cafdb760ca7":{
      "scriptId":"u4"},
    "4f5e1e5f09c5439d9b3145a5b239ff24":{
      "scriptId":"u5"}}});