$axure.loadCurrentPage({
  "url":"注册成功.html",
  "generationDate":new Date(1383038955655.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/系统登录默认页/bg.jpg",
    "width":1000,
    "height":750},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"ed134b2bc7f949d089cef296f7e84c60",
    "type":"Axure:Page",
    "name":"注册成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"460aff69d326454db412d2ce1514ea7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":162},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1639b7318f09462d975df77e011bdabf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":162},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2168250cea454bf598284ca131292b39",
          "label":"菜单",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":170},
            "size":{
              "width":141,
              "height":520}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"12de07e4db6f49f3b059821264074737",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"26ee39431e494812b8f7eb29200591fd",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":10}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"8738c122bb0b4dd8b9cfc8b7b38e1aa4",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":18},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9593b9c88fbb402d880eb0aef1d8a1d6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":18},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 用户管理",
                              "target":{
                                "targetType":"page",
                                "url":"用户管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ae9a22af6b044161a5d37c8a60dcb285",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":43}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"ef85111489db42f0b199f546178a9380",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":51},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"540aa35d3a114afa9f9ecd8bac382116",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":51},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 注册新会员",
                              "target":{
                                "targetType":"page",
                                "url":"注册新会员.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"06db65c496254602ae8cdc8e6ba4ebf1",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":176},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"3f130c4faa5d4162b587e622fa660bcc",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":184},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5564cb085e4a44cb8645ea18e70d45de",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":184},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 汇款充值",
                              "target":{
                                "targetType":"page",
                                "url":"汇款充值.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"efbde381c9b44cc999e27d003ff04553",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":209},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"63472a5695ee4506847c7035bc3de05f",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":217},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"983379fdf753407a8e5f2f72535f853b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":217},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 报单购物",
                              "target":{
                                "targetType":"page",
                                "url":"报单购物.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e32942c026e7497fbe38cf8487aa0629",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":242},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"96530caba9e54ac789c8c1f45fb6caa1",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":250},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a48922b90d7d4e12a393b824206712cf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":250},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 奖励查询",
                              "target":{
                                "targetType":"page",
                                "url":"奖励查询.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c6623c0b90d14285aa80eb53ad762540",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":275},
                    "size":{
                      "width":141,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "masterId":"d2415d04c3894ee2a19022d44e11f35b"},
{
                  "id":"46169b562f194bff99135419d8ab211b",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":283},
                    "size":{
                      "width":53,
                      "height":16},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e93993fc13514a9c912c437dc0c92830",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":283},
                        "size":{
                          "width":53,
                          "height":16},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 公告管理",
                              "target":{
                                "targetType":"page",
                                "url":"公告管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4cde855aa6fa489baf4a24b7798940ae",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF00,
                      "opacity":1},
                    "location":{
                      "x":31,
                      "y":85},
                    "size":{
                      "width":78,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d268bc0ad18046bb83fc6de9e6221947",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF00,
                          "opacity":1},
                        "location":{
                          "x":31,
                          "y":85},
                        "size":{
                          "width":78,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 注册新会员",
                              "target":{
                                "targetType":"page",
                                "url":"注册新会员.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"51ee4eab80b2417fb651e78f984a02cb",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":107},
                    "size":{
                      "width":78,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"89c1784f27f24a8dbb5ed00e8edf65c0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":107},
                        "size":{
                          "width":78,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 新会员管理",
                              "target":{
                                "targetType":"page",
                                "url":"新会员管理.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e4c37a05917843c9ae37e3e7b8f0f8b4",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":129},
                    "size":{
                      "width":91,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3eb52831f45b43b88432c27090cc11c9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":129},
                        "size":{
                          "width":91,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 修改本人资料",
                              "target":{
                                "targetType":"page",
                                "url":"修改本人资料.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"53d38d08d2e04c7da37b12837239c739",
                  "label":"",
                  "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":150},
                    "size":{
                      "width":91,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a5ff5bf38b44ed381b6fdf1f91ef654",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2168250cea454bf598284ca131292b39",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":150},
                        "size":{
                          "width":91,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 修改本人密码",
                              "target":{
                                "targetType":"page",
                                "url":"修改本人密码.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"15cbe2029bf74202b5da9a1343ec4a29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":70},
            "size":{
              "width":152,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cba7682804544eabaab812417e0b8d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":70},
                "size":{
                  "width":152,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4fb5747e7d245c0a9a36c3243e5656e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":162},
            "size":{
              "width":73,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d0294b1130b4e56ab35e5cbda11dfd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":162},
                "size":{
                  "width":73,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50e0766e9326455e8679ba65f90156c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xA5006600},
                "linePattern":"solid"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFDFEACA},
            "location":{
              "x":793,
              "y":466},
            "size":{
              "width":87,
              "height":24},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF6DB847},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5b3cd6fb49249c0a8d2ac910ae9a938",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xA5006600},
                    "linePattern":"solid"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFDFEACA},
                "location":{
                  "x":793,
                  "y":466},
                "size":{
                  "width":87,
                  "height":24},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF6DB847},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 ",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/注册表单/u84.png",
            "mouseOver~":"images/注册表单/u84_mouseOver.png"}},
{
          "id":"3a0c50072adb4600a90fa337ad504827",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":261,
              "y":216},
            "size":{
              "width":619,
              "height":240}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7770498485b49338a5e613a96bb4ba6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":261,
                  "y":216},
                "size":{
                  "width":619,
                  "height":240}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 报单购物表单",
                      "target":{
                        "targetType":"page",
                        "url":"报单购物表单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6665e43db058489890a3cd10ee206578",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":424,
              "y":216},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"098ac0e833f544d3833c6da4800bd543",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":424,
                  "y":216},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户管理/u347.png"}},
{
          "id":"c233458ecd8d455c9a3fa940681fe235",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":261,
              "y":379},
            "size":{
              "width":157,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ad8a7b6bd7840dabcb67cbb889e1760",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":261,
                  "y":379},
                "size":{
                  "width":157,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e54f717c7354d9da4248d1bf9f09fea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":263,
              "y":423},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf2e69a772e24269b748a62934699ebe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":263,
                  "y":423},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8acd9b1333e9495bb86000b0cdb28fe5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":260,
              "y":400},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7804fd371dc94ea29b67c6c744a42db4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":260,
                  "y":400},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b039fde4c2644bd187c4b5db6ea2a70f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":306,
              "y":15},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"699b9f5fbae64f4c9e6dfa3a4437dae7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":15},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0187d6aa2fbe4383887e7bd6198d05d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":408,
              "y":15},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"675cecf166b142468b24468bd7282c04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":408,
                  "y":15},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c13e170bd3224370845f3ea74fe059a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":785,
              "y":15},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4e3c34e27564c26af4874fed89f0a85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":785,
                  "y":15},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改本人密码",
                      "target":{
                        "targetType":"page",
                        "url":"修改本人密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90b1f5266e85420baa2e2e259a80ebf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":868,
              "y":15},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2422427a450488ca6d699b7acf44cee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":868,
                  "y":15},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04b28f47a4b44d568c4507d1983e3946",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":617,
              "y":15},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a22e2e2276f54084a1302c2590715924",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":617,
                  "y":15},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 系统登录默认页",
                      "target":{
                        "targetType":"page",
                        "url":"系统登录默认页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c09d96ec4ce947f0bc1cee9525794079",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":708,
              "y":15},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a5b9b4bd5db41e9bb2ec64f88ed15a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":708,
                  "y":15},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5eb1ba3ddef84a64a867878da46819cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":737,
              "y":15},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"650652ecc8d94eae953412a213121639",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":737,
                  "y":15},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u121.png"}},
{
          "id":"13daa890911b492894ceafd5ae9a65ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":756,
              "y":15},
            "size":{
              "width":20,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d789993fe8c4f5696bfe5294b0092ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":756,
                  "y":15},
                "size":{
                  "width":20,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e66c13bbdad42d39f91c600b3df1f63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":671,
              "y":15},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07272987684842e981ff0647675bf48f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":671,
                  "y":15},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 留言管理",
                      "target":{
                        "targetType":"page",
                        "url":"留言管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84a40766c835438e8944eb3c6099988b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":526,
              "y":14},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e00f87feadae4e8f9c19f7e4d085a334",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":526,
                  "y":14},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 购物车",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/系统登录默认页/u127.png"}},
{
          "id":"d1c9c2697e7d408d823334994e102adc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":3},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"301b9d1bb1dd4191b7d27f79b82a258d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":542,
                  "y":3},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/系统登录默认页/u129.png"}},
{
          "id":"51123d5763574c9789d0d7e2f243aec3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":547,
              "y":1},
            "size":{
              "width":42,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea7518fc865f40eb808b26867d898654",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":547,
                  "y":1},
                "size":{
                  "width":42,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "d2415d04c3894ee2a19022d44e11f35b":{
      "packageId":"d2415d04c3894ee2a19022d44e11f35b",
      "type":"Axure:Master",
      "name":"nav",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7837bfaf60f741f3a6519b77012fd40a",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
},
            "adaptiveStyles":{
},
            "masterId":"7a89eecc0e584f76adbdcdcf2a6c58e7"}]}},
    "7a89eecc0e584f76adbdcdcf2a6c58e7":{
      "packageId":"7a89eecc0e584f76adbdcdcf2a6c58e7",
      "type":"Axure:Master",
      "name":"nav1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"82d5041198434b178bff196e00dfbfe6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":141,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7824ebb366034aba98ee9785a7394f11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":141,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg",
              "normal~":"images/系统登录默认页/u5.jpg"}}]}}},
  "objectPaths":{
    "460aff69d326454db412d2ce1514ea7d":{
      "scriptId":"u0"},
    "1639b7318f09462d975df77e011bdabf":{
      "scriptId":"u1"},
    "2168250cea454bf598284ca131292b39":{
      "scriptId":"u2"},
    "26ee39431e494812b8f7eb29200591fd":{
      "scriptId":"u3",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u4",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u5"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u6"}}},
    "8738c122bb0b4dd8b9cfc8b7b38e1aa4":{
      "scriptId":"u7"},
    "9593b9c88fbb402d880eb0aef1d8a1d6":{
      "scriptId":"u8"},
    "ae9a22af6b044161a5d37c8a60dcb285":{
      "scriptId":"u9",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u10",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u11"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u12"}}},
    "ef85111489db42f0b199f546178a9380":{
      "scriptId":"u13"},
    "540aa35d3a114afa9f9ecd8bac382116":{
      "scriptId":"u14"},
    "06db65c496254602ae8cdc8e6ba4ebf1":{
      "scriptId":"u15",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u16",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u17"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u18"}}},
    "3f130c4faa5d4162b587e622fa660bcc":{
      "scriptId":"u19"},
    "5564cb085e4a44cb8645ea18e70d45de":{
      "scriptId":"u20"},
    "efbde381c9b44cc999e27d003ff04553":{
      "scriptId":"u21",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u22",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u23"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u24"}}},
    "63472a5695ee4506847c7035bc3de05f":{
      "scriptId":"u25"},
    "983379fdf753407a8e5f2f72535f853b":{
      "scriptId":"u26"},
    "e32942c026e7497fbe38cf8487aa0629":{
      "scriptId":"u27",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u28",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u29"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u30"}}},
    "96530caba9e54ac789c8c1f45fb6caa1":{
      "scriptId":"u31"},
    "a48922b90d7d4e12a393b824206712cf":{
      "scriptId":"u32"},
    "c6623c0b90d14285aa80eb53ad762540":{
      "scriptId":"u33",
      "7837bfaf60f741f3a6519b77012fd40a":{
        "scriptId":"u34",
        "82d5041198434b178bff196e00dfbfe6":{
          "scriptId":"u35"},
        "7824ebb366034aba98ee9785a7394f11":{
          "scriptId":"u36"}}},
    "46169b562f194bff99135419d8ab211b":{
      "scriptId":"u37"},
    "e93993fc13514a9c912c437dc0c92830":{
      "scriptId":"u38"},
    "4cde855aa6fa489baf4a24b7798940ae":{
      "scriptId":"u39"},
    "d268bc0ad18046bb83fc6de9e6221947":{
      "scriptId":"u40"},
    "51ee4eab80b2417fb651e78f984a02cb":{
      "scriptId":"u41"},
    "89c1784f27f24a8dbb5ed00e8edf65c0":{
      "scriptId":"u42"},
    "e4c37a05917843c9ae37e3e7b8f0f8b4":{
      "scriptId":"u43"},
    "3eb52831f45b43b88432c27090cc11c9":{
      "scriptId":"u44"},
    "53d38d08d2e04c7da37b12837239c739":{
      "scriptId":"u45"},
    "6a5ff5bf38b44ed381b6fdf1f91ef654":{
      "scriptId":"u46"},
    "15cbe2029bf74202b5da9a1343ec4a29":{
      "scriptId":"u47"},
    "6cba7682804544eabaab812417e0b8d6":{
      "scriptId":"u48"},
    "c4fb5747e7d245c0a9a36c3243e5656e":{
      "scriptId":"u49"},
    "8d0294b1130b4e56ab35e5cbda11dfd6":{
      "scriptId":"u50"},
    "50e0766e9326455e8679ba65f90156c8":{
      "scriptId":"u51"},
    "b5b3cd6fb49249c0a8d2ac910ae9a938":{
      "scriptId":"u52"},
    "3a0c50072adb4600a90fa337ad504827":{
      "scriptId":"u53"},
    "e7770498485b49338a5e613a96bb4ba6":{
      "scriptId":"u54"},
    "6665e43db058489890a3cd10ee206578":{
      "scriptId":"u55"},
    "098ac0e833f544d3833c6da4800bd543":{
      "scriptId":"u56"},
    "c233458ecd8d455c9a3fa940681fe235":{
      "scriptId":"u57"},
    "8ad8a7b6bd7840dabcb67cbb889e1760":{
      "scriptId":"u58"},
    "6e54f717c7354d9da4248d1bf9f09fea":{
      "scriptId":"u59"},
    "cf2e69a772e24269b748a62934699ebe":{
      "scriptId":"u60"},
    "8acd9b1333e9495bb86000b0cdb28fe5":{
      "scriptId":"u61"},
    "7804fd371dc94ea29b67c6c744a42db4":{
      "scriptId":"u62"},
    "b039fde4c2644bd187c4b5db6ea2a70f":{
      "scriptId":"u63"},
    "699b9f5fbae64f4c9e6dfa3a4437dae7":{
      "scriptId":"u64"},
    "0187d6aa2fbe4383887e7bd6198d05d8":{
      "scriptId":"u65"},
    "675cecf166b142468b24468bd7282c04":{
      "scriptId":"u66"},
    "c13e170bd3224370845f3ea74fe059a3":{
      "scriptId":"u67"},
    "d4e3c34e27564c26af4874fed89f0a85":{
      "scriptId":"u68"},
    "90b1f5266e85420baa2e2e259a80ebf4":{
      "scriptId":"u69"},
    "c2422427a450488ca6d699b7acf44cee":{
      "scriptId":"u70"},
    "04b28f47a4b44d568c4507d1983e3946":{
      "scriptId":"u71"},
    "a22e2e2276f54084a1302c2590715924":{
      "scriptId":"u72"},
    "c09d96ec4ce947f0bc1cee9525794079":{
      "scriptId":"u73"},
    "1a5b9b4bd5db41e9bb2ec64f88ed15a5":{
      "scriptId":"u74"},
    "5eb1ba3ddef84a64a867878da46819cd":{
      "scriptId":"u75"},
    "650652ecc8d94eae953412a213121639":{
      "scriptId":"u76"},
    "13daa890911b492894ceafd5ae9a65ed":{
      "scriptId":"u77"},
    "0d789993fe8c4f5696bfe5294b0092ef":{
      "scriptId":"u78"},
    "4e66c13bbdad42d39f91c600b3df1f63":{
      "scriptId":"u79"},
    "07272987684842e981ff0647675bf48f":{
      "scriptId":"u80"},
    "84a40766c835438e8944eb3c6099988b":{
      "scriptId":"u81"},
    "e00f87feadae4e8f9c19f7e4d085a334":{
      "scriptId":"u82"},
    "d1c9c2697e7d408d823334994e102adc":{
      "scriptId":"u83"},
    "301b9d1bb1dd4191b7d27f79b82a258d":{
      "scriptId":"u84"},
    "51123d5763574c9789d0d7e2f243aec3":{
      "scriptId":"u85"},
    "ea7518fc865f40eb808b26867d898654":{
      "scriptId":"u86"}}});